name: Get prebuilt shared
inputs:
  node:
    description: Node version
    required: true
runs:
  using: composite
  steps:
    - name: Get prebuilt shared
      uses: actions/download-artifact@v3
      with:
        name: "shared_${{ runner.os }}_${{ inputs.node }}"
    - name: Unpack shared
      shell: bash
      run: |
        set -e
        zstd -d shared.tar.zst
        tar xf shared.tar
        rm shared.tar*