import { ADMINISTRATION_STATUS } from '@tamanu/constants';
import { useDateTime } from '@tamanu/ui-components';

/**
 * Recording anomaly flags for a MAR dose cell.
 * @param {Object} props
 * @param {Object} [props.marInfo]
 * @param {Object} [props.medication]
 * @param {Array} [props.marDoses]
 * @param {boolean} props.isPaused
 * @param {boolean} props.isPast
 */
export default function useMarDoseAlerts({ marInfo, medication, marDoses, isPaused, isPast }) {
  const { storedDateTimeToEpochMilliseconds } = useDateTime();

  const { dueAt, recordedAt, status, isAutoGenerated } = marInfo || {};
  const { doseAmount, isPrn, isVariableDose } = medication || {};

  const recordedAtMs = storedDateTimeToEpochMilliseconds(recordedAt);
  const dueAtMs = storedDateTimeToEpochMilliseconds(dueAt);
  const isRecordedOutsideAdministrationSchedule =
    !isAutoGenerated ||
    (recordedAtMs != null && dueAtMs != null && recordedAtMs < dueAtMs) ||
    (isPrn && isPast);
  const isDoseAmountNotMatch =
    !isVariableDose &&
    status === ADMINISTRATION_STATUS.GIVEN &&
    marDoses?.some(dose => Number(dose.doseAmount) !== Number(doseAmount));
  const isRecordedDuringPaused = Boolean(recordedAt) && isPaused;
  const isMultipleDoses = marDoses?.length > 1;
  const isError = marInfo?.isError;
  const isAlert =
    Boolean(recordedAt) &&
    (isRecordedOutsideAdministrationSchedule ||
      isDoseAmountNotMatch ||
      isRecordedDuringPaused ||
      isMultipleDoses ||
      isError);

  return {
    isAlert,
    isDoseAmountNotMatch,
    isError,
    isRecordedDuringPaused,
    isRecordedOutsideAdministrationSchedule,
  };
}
