import { DataTypes, Op, type Transaction } from 'sequelize';
import { ADMINISTRATION_FREQUENCIES, SYNC_DIRECTIONS, SYSTEM_USER_UUID } from '@tamanu/constants';
import {
  addDays,
  addHours,
  addMonths,
  endOfDay,
  getDate,
  isValid,
  setDate,
  startOfDay,
} from 'date-fns';
import config from 'config';
import { getFirstAdministrationDate } from '@tamanu/shared/utils/medication';
import { Model } from './Model';
import { dateTimeType, type InitOptions, type Models } from '../types/model';
import type { Prescription } from './Prescription';
import type { Encounter } from './Encounter';
import { getCurrentDateTimeString } from '@tamanu/utils/dateTime';

export class MedicationAdministrationRecord extends Model {
  declare id: string;
  declare status?: string;
  declare dueAt: string;
  declare recordedAt?: string;
  declare isAutoGenerated?: boolean;
  declare prescriptionId?: string;
  declare changingStatusReason?: string;
  declare reasonNotGivenId?: string;
  declare changingNotGivenInfoReason?: string;
  declare recordedByUserId?: string;
  declare isError?: boolean;
  declare errorNotes?: string;

  static initModel({ primaryKey, ...options }: InitOptions, models: Models) {
    super.init(
      {
        id: primaryKey,
        status: DataTypes.STRING,
        dueAt: dateTimeType('dueAt', {
          allowNull: false,
        }),
        recordedAt: dateTimeType('recordedAt', {
          allowNull: true,
        }),
        isAutoGenerated: DataTypes.BOOLEAN,
        changingStatusReason: DataTypes.TEXT,
        changingNotGivenInfoReason: DataTypes.TEXT,
        isError: DataTypes.BOOLEAN,
        errorNotes: DataTypes.TEXT,
      },
      {
        ...options,
        syncDirection: SYNC_DIRECTIONS.BIDIRECTIONAL,
        hooks: {
          afterCreate: async (mar: MedicationAdministrationRecord) => {
            // If the prescription is immediately and the MAR is the first time being not given, then discontinue the prescription
            // https://linear.app/bes/issue/EPI-1143/automatically-discontinue-prescriptions-with-frequency-of-immediately
            const prescription = await models.Prescription.findByPk(mar.prescriptionId);
            if (
              prescription?.frequency === ADMINISTRATION_FREQUENCIES.IMMEDIATELY &&
              !prescription?.discontinued &&
              mar.status
            ) {
              Object.assign(prescription, {
                discontinuingReason: 'STAT dose recorded',
                discontinuingClinicianId: SYSTEM_USER_UUID,
                discontinuedDate: getCurrentDateTimeString(),
                discontinued: true,
              });
              await prescription.save();
            }
          },
          afterUpdate: async (mar: MedicationAdministrationRecord) => {
            // If the prescription is immediately and the MAR is the first time being not given, then discontinue the prescription
            // https://linear.app/bes/issue/EPI-1143/automatically-discontinue-prescriptions-with-frequency-of-immediately
            const prescription = await models.Prescription.findByPk(mar.prescriptionId);
            if (
              prescription?.frequency === ADMINISTRATION_FREQUENCIES.IMMEDIATELY &&
              !prescription?.discontinued &&
              mar.status
            ) {
              Object.assign(prescription, {
                discontinuingReason: 'STAT dose recorded',
                discontinuingClinicianId: SYSTEM_USER_UUID,
                discontinuedDate: getCurrentDateTimeString(),
                discontinued: true,
              });
              await prescription.save();
            }
          },
        },
      },
    );
  }

  /**
   * Generates upcoming Medication Administration Records (MARs) for a given prescription.
   *
   * This function calculates and creates MAR entries based on the prescription's
   * frequency, start date, end date, ideal administration times, and discontinuation date.
   * It ensures that MARs are generated up to a configurable timeframe in the future
   * (defaulting to 72 hours) or until the prescription's end date, whichever is earlier.
   *
   * Special handling is included for 'IMMEDIATELY' and 'AS_DIRECTED' frequencies,
   * as well as for calculating next due dates for various frequencies like
   * 'EVERY_SECOND_DAY', 'ONCE_A_WEEK', and 'ONCE_A_MONTH'.
   *
   * It avoids creating duplicate records by checking the last existing MAR and
   * skips generation if the calculated due date falls outside the valid prescription period
   * or before the last generated MAR.
   *
   * @param prescription The prescription object for which to generate MARs.
   */
  static async generateMedicationAdministrationRecords(prescription: Prescription) {
    if (!prescription.frequency || !prescription.startDate) {
      return;
    }

    // Get the last MAR of the prescription (for cron job)
    const lastMedicationAdministrationRecord = await this.findOne({
      where: {
        prescriptionId: prescription.id,
      },
      order: [['dueAt', 'DESC']],
    });

    // If the prescription is immediately or as directed, create a MAR for the start date
    if (
      prescription.frequency === ADMINISTRATION_FREQUENCIES.IMMEDIATELY ||
      prescription.frequency === ADMINISTRATION_FREQUENCIES.AS_DIRECTED
    ) {
      if (!lastMedicationAdministrationRecord) {
        await this.create({
          prescriptionId: prescription.id,
          dueAt: prescription.startDate,
          isAutoGenerated: true,
        });
      }
      return;
    }

    // Get the first administration date for the prescription
    let firstAdministrationDate: Date | undefined;
    if (prescription.idealTimes && prescription.idealTimes.length > 0) {
      try {
        firstAdministrationDate = getFirstAdministrationDate(
          new Date(prescription.startDate),
          prescription.idealTimes,
        );
      } catch (error) {
        console.error(
          `Error calculating first administration date for prescription ${prescription.id}:`,
          error,
        );
      }
    }

    // Get the upcoming records should be generated time frame
    const upcomingRecordsShouldBeGeneratedTimeFrame =
      config?.medicationAdministrationRecord?.upcomingRecordsShouldBeGeneratedTimeFrame || 72;

    let endDate = endOfDay(addHours(new Date(), upcomingRecordsShouldBeGeneratedTimeFrame));

    // Override with prescription end date if it's earlier
    if (prescription.endDate && new Date(prescription.endDate) < endDate) {
      endDate = new Date(prescription.endDate);
    }

    // Get the last due date for the prescription
    let lastDueDate: Date;
    if (lastMedicationAdministrationRecord) {
      lastDueDate = new Date(lastMedicationAdministrationRecord.dueAt);
    } else if (firstAdministrationDate) {
      lastDueDate = firstAdministrationDate;
    } else {
      lastDueDate = new Date(prescription.startDate);
    }

    // Generate the upcoming MARs
    while (lastDueDate < endDate) {
      for (const idealTime of prescription.idealTimes || []) {
        const [hours, minutes] = idealTime.split(':').map(Number);
        const nextDueDate = new Date(
          lastDueDate.getFullYear(),
          lastDueDate.getMonth(),
          lastDueDate.getDate(),
          hours,
          minutes,
          0,
        );
        // Skip if the next due date is before the start date, after the end date, or after the prescription was discontinued
        // For cron job, skip if the next due date is before the last due date (to avoid creating duplicate records)
        if (
          nextDueDate < new Date(prescription.startDate) ||
          nextDueDate > endDate ||
          (lastMedicationAdministrationRecord &&
            nextDueDate < new Date(lastMedicationAdministrationRecord.dueAt)) ||
          (prescription.discontinuedDate && nextDueDate >= new Date(prescription.discontinuedDate))
        ) {
          continue;
        }

        // Skip if administration date is not valid (required to pass unit tests)
        if (isValid(nextDueDate)) {
          await this.create({
            prescriptionId: prescription.id,
            dueAt: nextDueDate,
            isAutoGenerated: true,
          });
        }
      }
      // Get next administration date based on frequency
      switch (prescription.frequency) {
        case ADMINISTRATION_FREQUENCIES.EVERY_SECOND_DAY:
          lastDueDate = startOfDay(addDays(lastDueDate, 2));
          break;
        case ADMINISTRATION_FREQUENCIES.ONCE_A_WEEK:
          lastDueDate = startOfDay(addDays(lastDueDate, 7));
          break;
        case ADMINISTRATION_FREQUENCIES.ONCE_A_MONTH: {
          // If the due date of the first administration is the 29th or 30th, then set the next due date to the 1st of the next month
          const lastDueDay = getDate(lastDueDate);
          if (lastDueDay >= 29) {
            lastDueDate = startOfDay(setDate(addMonths(lastDueDate, 2), 1));
          } else {
            lastDueDate = startOfDay(setDate(addMonths(lastDueDate, 1), lastDueDay));
          }
          break;
        }
        default:
          lastDueDate = startOfDay(addDays(lastDueDate, 1));
          break;
      }
    }
  }

  static async onEncounterDischarged(encounter: Encounter, transaction?: Transaction) {
    const { models } = this.sequelize;
    const encounterId = encounter.id;

    const encounterPrescriptions = await models.EncounterPrescription.findAll({
      where: {
        encounterId,
      },
      attributes: ['prescriptionId'],
      transaction,
    });

    await models.MedicationAdministrationRecord.destroy({
      where: {
        dueAt: {
          [Op.gt]: encounter.endDate,
        },
        prescriptionId: {
          [Op.in]: encounterPrescriptions.map(
            (encounterPrescription) => encounterPrescription.prescriptionId,
          ),
        },
        status: null,
      },
      transaction,
    });
  }

  static async onPrescriptionDiscontinued(
    prescription: Prescription,
    transaction?: Transaction | null,
  ) {
    const { models } = this.sequelize;

    await models.MedicationAdministrationRecord.destroy({
      where: {
        prescriptionId: prescription.id,
        dueAt: {
          [Op.gt]: prescription.discontinuedDate,
        },
        status: null,
      },
      transaction,
    });
  }

  static getListReferenceAssociations() {
    return ['prescription'];
  }

  static initRelations(models: Models) {
    this.belongsTo(models.Prescription, {
      foreignKey: 'prescriptionId',
      as: 'prescription',
    });
    this.belongsTo(models.ReferenceData, {
      foreignKey: 'reasonNotGivenId',
      as: 'reasonNotGiven',
    });
    this.hasMany(models.MedicationAdministrationRecordDose, {
      foreignKey: 'marId',
      as: 'doses',
    });
    this.belongsTo(models.User, {
      foreignKey: 'recordedByUserId',
      as: 'recordedByUser',
    });
    this.hasMany(models.Note, {
      foreignKey: 'recordId',
      as: 'notes',
      constraints: false,
      scope: {
        recordType: this.name,
      },
    });
  }

  static buildSyncFilter() {
    return null; // syncs everywhere
  }

  static buildSyncLookupQueryDetails() {
    return null; // syncs everywhere
  }
}
