/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

const fileMap = {
  
  "ask-ai.baml": "generator target {\n  output_type \"typescript\"\n  output_dir \".\"\n  version \"0.220.0\"\n}\n\nclient<llm> AnthropicClient {\n  provider anthropic\n  options {\n    model \"claude-sonnet-4-6\"\n    api_key env.ANTHROPIC_API_KEY\n  }\n}\n\nclass RagSource {\n  filePath string\n  excerpt string\n}\n\nclass AskAiResponse {\n  answer string\n  sources RagSource[]\n  cannotAnswer bool\n}\n\nfunction AskTamanu(\n  userQuestion: string,\n  ragContext: string,\n  conversationHistory: string,\n) -> AskAiResponse {\n  client AnthropicClient\n  prompt #\"\n    You are a helpful assistant for Tamanu, a healthcare management system used by\n    clinical staff in Pacific Island nations and similar contexts.\n    Answer questions about how Tamanu works — features, workflows, and known errors.\n    Use only the provided context. Do not guess or invent features.\n    If the context does not contain enough information to answer, set cannotAnswer to true\n    and leave answer and sources empty.\n    Use plain language suitable for clinical staff who are not software developers.\n    Tamanu has two server types: the facility server (used at individual health facilities)\n    and the central server (used for system-wide administration and reporting).\n    If a feature or workflow is only available on one of these server types, say so clearly\n    (e.g. \"This is only available on the facility server.\" or \"This is only available on the central server.\").\n\n    Context from Tamanu documentation and codebase:\n    {{ ragContext }}\n\n    Conversation so far:\n    {{ conversationHistory }}\n\n    User question: {{ userQuestion }}\n\n    {{ ctx.output_format }}\n  \"#\n}\n",
}
export const getBamlFiles = () => {
    return fileMap;
}