/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { BamlStream } from "@boundaryml/baml"

export interface VarNotification<T> {
  variable_name: string
  value: T
  timestamp: string
  function_name: string
}

// Internal stream notification from Rust FFI
interface InternalStreamEvent {
  streamId: string
  notificationType: "start" | "update" | "end"
  value?: any
}

// Simple async iterable stream for watch notifications

type VarHandler<T> = (event: VarNotification<T>) => void
type StreamHandler<PartialT, FinalT> = (event: VarNotification<BamlStream<PartialT, FinalT>>) => void
type InternalStreamHandler = (event: InternalStreamEvent) => void

export interface InternalEventBindings {
  functionName: string
  vars: Record<string, VarHandler<any>[]>
  streams: Record<string, InternalStreamHandler[]>
  functions: Record<string, InternalEventBindings>
}

export interface EventCollectorInternal {
  __handlers(): InternalEventBindings
}

