version: 2
sources:
  - name: tamanu
    schema: public
    description: "{{ doc('logs__generic__schema') }}"
    tables:
      - name: patient_field_values
        description: ""
        tags:
          - patient
        columns:
          - name: created_at
            data_type: timestamp with time zone
            description: "{{ doc('generic__created_at') }} in patient_field_values."
            data_tests:
              - not_null
          - name: updated_at
            data_type: timestamp with time zone
            description: "{{ doc('generic__updated_at') }} in patient_field_values."
            data_tests:
              - not_null
          - name: deleted_at
            data_type: timestamp with time zone
            description: "{{ doc('generic__deleted_at') }} in patient_field_values."
          - name: value
            data_type: text
            description: "{{ doc('patient_field_values__value') }}"
            data_tests:
              - not_null
          - name: definition_id
            data_type: character varying(255)
            description: "{{ doc('patient_field_values__definition_id') }}"
            data_tests:
              - unique
              - not_null
          - name: patient_id
            data_type: character varying(255)
            description: "{{ doc('patient_field_values__patient_id') }}"
            data_tests:
              - unique
              - not_null
          - name: updated_at_sync_tick
            data_type: bigint
            description: "{{ doc('generic__updated_at_sync_tick') }} in
              patient_field_values."
            data_tests:
              - not_null
          - name: id
            data_type: text
            description: "{{ doc('generic__id') }} in patient_field_values."
