version: 2

sources:
  - name: tamanu
    schema: public
    description: "Tamanu database"
    tables:
      - name: settings
        description: ""
        tags: ['system']
        columns:
          - name: id
            data_type: uuid
            description: ""
          - name: created_at
            data_type: timestamp with time zone
            description: ""
          - name: updated_at
            data_type: timestamp with time zone
            description: ""
          - name: deleted_at
            data_type: timestamp with time zone
            description: ""
          - name: key
            data_type: text
            description: ""
          - name: value
            data_type: jsonb
            description: ""
          - name: facility_id
            data_type: character varying
            description: ""
          - name: updated_at_sync_tick
            data_type: bigint
            description: ""
          - name: scope
            data_type: text
            description: ""
