name: Common setup steps
inputs:
  node:
    description: Node version
    required: true
  get-shared:
    description: Retrieve prebuilt shared too
    required: true
    default: false
runs:
  using: composite
  steps:
    - name: Use Node.js ${{ inputs.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node }}
        cache: yarn
    
    - name: Get prebuilt shared
      if: inputs.get-shared == true
      uses: ./.github/actions/get-shared
      with:
        node: ${{ inputs.node }}