version: "3.8"
services:
  lan:
    build:
      context: .
      dockerfile: infra/docker/lan/Dockerfile
    ports:
      - "4000:4000"
    restart: on-failure
  sync-server:
    build:
      context: .
      dockerfile: infra/docker/sync-server/Dockerfile
    ports:
      - "3000:3000"
    restart: on-failure
  db:
    build:
      context: .
      dockerfile: infra/docker/postgres/Dockerfile
    volumes:
      - ./docker-volumes/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
