version: "3.8"
services:
  facility-server:
    build:
      context: .
      dockerfile: packages/facility-server/docker/Dockerfile
    ports:
      - "4000:4000"
    restart: on-failure
  central-server:
    build:
      context: .
      dockerfile: packages/central-server/docker/Dockerfile
    ports:
      - "3000:3000"
    restart: on-failure
  db:
    build:
      context: .
      dockerfile: packages/shared/docker/postgres/Dockerfile
    volumes:
      - ./docker-volumes/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
