### 

@localhost = http://localhost:3000
@devhost = https://sync-dev.tamanu.io
@host = {{localhost}}
@token = fake-token

###

# Meta server
GET https://meta.tamanu.io/servers

###

POST {{host}}/v1/login
Content-Type: application/json

{
    "email": "admin@tamanu.io",
    "password": "123455"
}

###

GET {{host}}/v1/sync/user?since=0
Authorization: Bearer fake-token
###

GET {{host}}/v1/whoami
Authorization: Bearer fake-token

###

POST {{host}}/v1/sync/user
Authorization: Bearer fake-token
Content-Type: application/json

{
    "data": {
    "email": "admin@tamanu.io",
    "displayName": "Initial Admin",
    "password": "123455",
    "role": "administrator"
    }
}

###
POST {{host}}/v1/sync/user
Authorization: Bearer fake-token
Content-Type: application/json

{
    "data": {
    "email": "admin@tamanu.io",
    "displayName": "Initial Admin",
    "password": "123455",
    "role": "administrator"
    }
}