// Patients
export const CREATE_PATIENT_REQUEST = 'patients/CREATE_PATIENT_REQUEST';
export const CREATE_PATIENT_SUCCESS = 'patients/CREATE_PATIENT_SUCCESS';
export const CREATE_PATIENT_FAILED = 'patients/CREATE_PATIENT_FAILED';

export const FETCH_PATIENTS_REQUEST = 'patients/FETCH_PATIENTS_REQUEST';
export const FETCH_PATIENTS_SUCCESS = 'patients/FETCH_PATIENTS_SUCCESS';
export const FETCH_PATIENTS_FAILED = 'patients/FETCH_PATIENTS_FAILED';

// Medications
export const CREATE_MEDICATION_REQUEST = 'patients/CREATE_PATIENT_REQUEST';
export const CREATE_MEDICATION_SUCCESS = 'patients/CREATE_PATIENT_SUCCESS';
export const CREATE_MEDICATION_FAILED = 'patients/CREATE_PATIENT_FAILED';

export const FETCH_MEDICATIONS_REQUEST = 'medications/FETCH_MEDICATIONS_REQUEST';
export const FETCH_MEDICATIONS_SUCCESS = 'medications/FETCH_MEDICATIONS_SUCCESS';
export const FETCH_MEDICATIONS_FAILED = 'medications/FETCH_MEDICATIONS_FAILED';
