// Patients
export const CREATE_PATIENT_REQUEST = 'patients/CREATE_PATIENT_REQUEST';
export const CREATE_PATIENT_SUCCESS = 'patients/CREATE_PATIENT_SUCCESS';
export const CREATE_PATIENT_FAILED = 'patients/CREATE_PATIENT_FAILED';

export const FETCH_PATIENTS_REQUEST = 'patients/FETCH_PATIENTS_REQUEST';
export const FETCH_PATIENTS_SUCCESS = 'patients/FETCH_PATIENTS_SUCCESS';
export const FETCH_PATIENTS_FAILED = 'patients/FETCH_PATIENTS_FAILED';

// Medications
export const CREATE_MEDICATION_REQUEST = 'medications/CREATE_PATIENT_REQUEST';
export const CREATE_MEDICATION_SUCCESS = 'medications/CREATE_PATIENT_SUCCESS';
export const CREATE_MEDICATION_FAILED = 'medications/CREATE_PATIENT_FAILED';

export const FETCH_MEDICATIONS_REQUEST = 'medications/FETCH_MEDICATIONS_REQUEST';
export const FETCH_MEDICATIONS_SUCCESS = 'medications/FETCH_MEDICATIONS_SUCCESS';
export const FETCH_MEDICATIONS_FAILED = 'medications/FETCH_MEDICATIONS_FAILED';

export const CREATE_DISPENSE_REQUEST = 'medications/CREATE_DISPENSE_REQUEST';
export const CREATE_DISPENSE_SUCCESS = 'medications/CREATE_DISPENSE_SUCCESS';
export const CREATE_DISPENSE_FAILED = 'medications/CREATE_DISPENSE_FAILED';

// Invoices
export const CREATE_INVOICE_REQUEST = 'invoices/CREATE_INVOICE_REQUEST';
export const CREATE_INVOICE_SUCCESS = 'invoices/CREATE_INVOICE_SUCCESS';
export const CREATE_INVOICE_FAILED = 'invoices/CREATE_INVOICE_FAILED';

export const FETCH_INVOICES_REQUEST = 'invoices/FETCH_INVOICES_REQUEST';
export const FETCH_INVOICES_SUCCESS = 'invoices/FETCH_INVOICES_SUCCESS';
export const FETCH_INVOICES_FAILED = 'invoices/FETCH_INVOICES_FAILED';
