// Patients
export const CREATE_PATIENT_INDEXES_REQUEST = 'patients/CREATE_PATIENT_INDEXES_REQUEST';
export const CREATE_PATIENT_INDEXES_SUCCESS = 'patients/CREATE_PATIENT_INDEXES_SUCCESS';
export const CREATE_PATIENT_INDEXES_FAILED = 'patients/CREATE_PATIENT_INDEXES_FAILED';

export const CREATE_PATIENT_REQUEST = 'patients/CREATE_PATIENT_REQUEST';
export const CREATE_PATIENT_SUCCESS = 'patients/CREATE_PATIENT_SUCCESS';
export const CREATE_PATIENT_FAILED = 'patients/CREATE_PATIENT_FAILED';

export const FETCH_PATIENTS_REQUEST = 'patients/FETCH_PATIENTS_REQUEST';
export const FETCH_PATIENTS_SUCCESS = 'patients/FETCH_PATIENTS_SUCCESS';
export const FETCH_PATIENTS_FAILED = 'patients/FETCH_PATIENTS_FAILED';

export const FETCH_ADMITTED_PATIENTS_REQUEST = 'patients/FETCH_ADMITTED_PATIENTS_REQUEST';
export const FETCH_ADMITTED_PATIENTS_SUCCESS = 'patients/FETCH_ADMITTED_PATIENTS_SUCCESS';
export const FETCH_ADMITTED_PATIENTS_FAILED = 'patients/FETCH_ADMITTED_PATIENTS_FAILED';

export const FETCH_ONE_PATIENT_REQUEST = 'patients/FETCH_ONE_PATIENT_REQUEST';
export const FETCH_ONE_PATIENT_SUCCESS = 'patients/FETCH_ONE_PATIENT_SUCCESS';
export const FETCH_ONE_PATIENT_FAILED = 'patients/FETCH_ONE_PATIENT_FAILED';

export const DELETE_PATIENT_REQUEST = 'patients/DELETE_PATIENT_REQUEST';
export const DELETE_PATIENT_SUCCESS = 'patients/DELETE_PATIENT_SUCCESS';
export const DELETE_PATIENT_FAILED = 'patients/DELETE_PATIENT_FAILED';

export const CHECKIN_PATIENT_REQUEST = 'patients/CHECKIN_PATIENT_REQUEST';
export const CHECKIN_PATIENT_SUCCESS = 'patients/CHECKIN_PATIENT_SUCCESS';
export const CHECKIN_PATIENT_FAILED = 'patients/CHECKIN_PATIENT_FAILED';

export const GET_UPDATED_BIRTHDAY_REQUEST = 'patients/GET_UPDATED_BIRTHDAY_REQUEST';
export const GET_UPDATED_BIRTHDAY_SUCCESS = 'patients/GET_UPDATED_BIRTHDAY_SUCCESS';
export const GET_UPDATED_BIRTHDAY_FAILED = 'patients/GET_UPDATED_BIRTHDAY_FAILED';

export const GET_UPDATED_REFERDATE_REQUEST = 'patients/GET_UPDATED_REFERDATE_REQUEST';
export const GET_UPDATED_REFERDATE_SUCCESS = 'patients/GET_UPDATED_REFERDATE_SUCCESS';
export const GET_UPDATED_REFERDATE_FAILED = 'patients/GET_UPDATED_REFERDATE_FAILED';

// Visit
export const FETCH_VISIT_REQUEST = 'patients/FETCH_VISIT_REQUEST';
export const FETCH_VISIT_SUCCESS = 'patients/FETCH_VISIT_SUCCESS';
export const FETCH_VISIT_FAILED = 'patients/FETCH_VISIT_FAILED';

export const SAVE_VISIT_REQUEST = 'patients/SAVE_VISIT_REQUEST';
export const SAVE_VISIT_SUCCESS = 'patients/SAVE_VISIT_SUCCESS';
export const SAVE_VISIT_FAILED = 'patients/SAVE_VISIT_FAILED';
export const SAVE_VISIT_RESET = 'patients/SAVE_VISIT_RESET';

export const FETCH_PROCEDURE_REQUEST = 'visit/FETCH_PROCEDURE_REQUEST';
export const FETCH_PROCEDURE_SUCCESS = 'visit/FETCH_PROCEDURE_SUCCESS';
export const FETCH_PROCEDURE_FAILED = 'visit/FETCH_PROCEDURE_FAILED';

export const SAVE_PROCEDURE_REQUEST = 'visit/SAVE_PROCEDURE_REQUEST';
export const SAVE_PROCEDURE_SUCCESS = 'visit/SAVE_PROCEDURE_SUCCESS';
export const SAVE_PROCEDURE_FAILED = 'visit/SAVE_PROCEDURE_FAILED';

// Medications
export const FETCH_MEDICATION_REQUEST = 'medication/FETCH_MEDICATION_REQUEST';
export const FETCH_MEDICATION_SUCCESS = 'medication/FETCH_MEDICATION_SUCCESS';
export const FETCH_MEDICATION_FAILED = 'medication/FETCH_MEDICATION_FAILED';

export const SAVE_MEDICATION_REQUEST = 'medication/SAVE_MEDICATION_REQUEST';
export const SAVE_MEDICATION_SUCCESS = 'medication/SAVE_MEDICATION_SUCCESS';
export const SAVE_MEDICATION_FAILED = 'medication/SAVE_MEDICATION_FAILED';

export const CREATE_DISPENSE_REQUEST = 'medication/CREATE_DISPENSE_REQUEST';
export const CREATE_DISPENSE_SUCCESS = 'medication/CREATE_DISPENSE_SUCCESS';
export const CREATE_DISPENSE_FAILED = 'medication/CREATE_DISPENSE_FAILED';

export const FETCH_MEDICATIONS_REQUEST = 'medication/FETCH_MEDICATIONS_REQUEST';
export const FETCH_MEDICATIONS_SUCCESS = 'medication/FETCH_MEDICATIONS_SUCCESS';
export const FETCH_MEDICATIONS_FAILED = 'medication/FETCH_MEDICATIONS_FAILED';

// Invoices
export const CREATE_INVOICE_REQUEST = 'invoices/CREATE_INVOICE_REQUEST';
export const CREATE_INVOICE_SUCCESS = 'invoices/CREATE_INVOICE_SUCCESS';
export const CREATE_INVOICE_FAILED = 'invoices/CREATE_INVOICE_FAILED';

export const FETCH_INVOICES_REQUEST = 'invoices/FETCH_INVOICES_REQUEST';
export const FETCH_INVOICES_SUCCESS = 'invoices/FETCH_INVOICES_SUCCESS';
export const FETCH_INVOICES_FAILED = 'invoices/FETCH_INVOICES_FAILED';

// Labs
export const CREATE_LAB_REQUEST = 'labs/CREATE_LAB_REQUEST';
export const CREATE_LAB_SUCCESS = 'labs/CREATE_LAB_SUCCESS';
export const CREATE_LAB_FAILED = 'labs/CREATE_LAB_FAILED';

export const FETCH_LABS_REQUEST = 'labs/FETCH_LABS_REQUEST';
export const FETCH_LABS_SUCCESS = 'labs/FETCH_LABS_SUCCESS';
export const FETCH_LABS_FAILED = 'labs/FETCH_LABS_FAILED';

export const CREATE_APPOINTMENT_REQUEST = 'appointments/CREATE_APPOINTMENT_REQUEST';
export const CREATE_APPOINTMENT_SUCCESS = 'appointments/CREATE_APPOINTMENT_SUCCESS';
export const CREATE_APPOINTMENT_FAILED = 'appointments/CREATE_APPOINTMENT_FAILED';

// Programs
export const ANSWER_CHANGE = 'ANSWER_CHANGE';
export const ASSESSMENT_CLINIC_SELECT = 'ASSESSMENT_CLINIC_SELECT';
export const EXTRA_PROPS_CHANGE = 'EXTRA_PROPS_CHANGE';
export const INIT_SURVEY = 'INIT_SURVEY';
export const SURVEY_SCREEN_SELECT = 'SURVEY_SCREEN_SELECT';
export const SURVEY_SUBMIT = 'SURVEY_SUBMIT';
export const SURVEY_SUBMIT_SUCCESS = 'SURVEY_SUBMIT_SUCCESS';
export const UPDATE_SURVEYS = 'UPDATE_SURVEYS';
export const WIPE_CURRENT_SURVEY = 'WIPE_CURRENT_SURVEY';
export const ASSESSMENT_RESET = 'ASSESSMENT_RESET';
export const VALIDATION_ERROR_CHANGE = 'VALIDATION_ERROR_CHANGE';
export const SURVEY_SCREEN_ERROR_MESSAGE_CHANGE = 'SURVEY_SCREEN_ERROR_MESSAGE_CHANGE';

export const LOAD_SURVEYS_REQUEST = 'LOAD_SURVEYS_REQUEST';
export const LOAD_SURVEYS_SUCCESS = 'LOAD_SURVEYS_SUCCESS';
export const LOAD_SURVEYS_FAILED = 'LOAD_SURVEYS_FAILED';
export const LOAD_COMPLETED_SURVEYS_SUCCESS = 'LOAD_COMPLETED_SURVEYS_SUCCESS';

export const LOAD_RESPONSES_REQUEST = 'LOAD_RESPONSES_REQUEST';
export const LOAD_RESPONSES_SUCCESS = 'LOAD_RESPONSES_SUCCESS';
export const LOAD_RESPONSES_FAILED = 'LOAD_RESPONSES_FAILED';

export const LOAD_RESPONSE_REQUEST = 'LOAD_RESPONSE_REQUEST';
export const LOAD_RESPONSE_SUCCESS = 'LOAD_RESPONSE_SUCCESS';
export const LOAD_RESPONSE_FAILED = 'LOAD_RESPONSE_FAILED';
