export const PATIENT_FIELD_DEFINITION_TYPES = {
  STRING: 'STRING',
  NUMBER: 'NUMBER',
  SELECT: 'SELECT',
};
export const PATIENT_FIELD_DEFINITION_TYPE_VALUES = Object.values(PATIENT_FIELD_DEFINITION_TYPES);

export const PATIENT_FIELD_DEFINITION_STATES = {
  CURRENT: 'CURRENT',
  HISTORICAL: 'HISTORICAL',
};
export const PATIENT_FIELD_DEFINITION_STATE_VALUES = Object.values(PATIENT_FIELD_DEFINITION_STATES);
