import { describe, expect, it } from 'vitest';
import { htmlToPlainText } from '../../src/utils/fhir/htmlToPlainText';

describe('htmlToPlainText', () => {
  it.each([
    'Positive for markers X and Y',
    'Line one\nLine two\n\n  indented',
    'Range <10 or >20',
    'Glucose <5.5 mmol/L',
    'Ratio 3 < 4 & 5 > 2',
    'result: <patient_name>',
    'result: <patientname>',
    'result: <patient name>',
    'result: <Patient-Name>',
    'Positive <see attached>',
  ])('returns text without HTML tags unchanged: %j', text => {
    expect(htmlToPlainText(text)).toBe(text);
  });

  it('decodes entities and turns block elements into line breaks', () => {
    expect(htmlToPlainText('<p>Total &beta;-hCG&nbsp;level</p><p>Repeat<br/>in 48 hours</p>')).toBe(
      'Total β-hCG level\n\nRepeat\nin 48 hours',
    );
  });

  it('matches tags regardless of case and attributes', () => {
    expect(htmlToPlainText('<P class="x">Upper</P><SPAN style="color: red">case</SPAN>')).toBe(
      'Upper\n\ncase',
    );
  });

  it('keeps non-HTML angle brackets in content that also has HTML', () => {
    expect(htmlToPlainText('<p>Note: <b>bold</b> <patient_name></p><p>Range <10 or >20</p>')).toBe(
      'Note: bold <patient_name>\n\nRange <10 or >20',
    );
  });

  it('drops HTML comments', () => {
    expect(htmlToPlainText('<p>A</p><!-- generated by LIS --><p>B</p>')).toBe('A\n\nB');
  });

  it('renders tables as aligned rows', () => {
    expect(
      htmlToPlainText(
        '<table><tr><td>Week</td><td>Level</td></tr><tr><td>3</td><td><p>5 - 50</p></td></tr></table>',
      ),
    ).toBe('Week   Level\n3      5 - 50');
  });
});
