/** @see https://www.sqlite.org/limits.html#max_variable_number */
export const SQLITE_MAX_PARAMETERS = 32766;
/** @see https://www.sqlite.org/limits.html#max_expr_depth */
export const SQLITE_MAX_DEPTH_OF_EXPRESSION_TREE = 1000;

// The query generated by bulk inserts larger than this will throw
// a max depth error
export const MAX_RECORDS_IN_BULK_INSERT = SQLITE_MAX_DEPTH_OF_EXPRESSION_TREE - 3;
