export const DAYS_OF_WEEK = ['MO', 'TU', 'WE', 'TH', 'FR', 'SA', 'SU'];

export const REPEAT_FREQUENCY = {
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY',
};

export const REPEAT_FREQUENCY_VALUES = Object.values(REPEAT_FREQUENCY);

export const REPEAT_FREQUENCY_LABELS = {
  [REPEAT_FREQUENCY.WEEKLY]: 'Weekly',
  [REPEAT_FREQUENCY.MONTHLY]: 'Monthly',
};

export const REPEAT_FREQUENCY_UNIT_LABELS = {
  [REPEAT_FREQUENCY.WEEKLY]: 'Week',
  [REPEAT_FREQUENCY.MONTHLY]: 'Month',
};

export const REPEAT_FREQUENCY_UNIT_PLURAL_LABELS = {
  [REPEAT_FREQUENCY.WEEKLY]: 'weeks',
  [REPEAT_FREQUENCY.MONTHLY]: 'months',
};
