import { WS_EVENTS } from './webSocket';

export const MATERIALIZED_TABLES = {
  UPCOMING_VACCINATIONS: 'upcomingVaccinations',
};

export const MATERIALIZED_VIEW_CHANGE_EVENTS = {
  [MATERIALIZED_TABLES.UPCOMING_VACCINATIONS]: WS_EVENTS.UPCOMING_VACCINATIONS_CHANGE,
};
