import { OTHER_REFERENCE_TYPES, REFERENCE_TYPES } from './importable';

export const PORTAL_ONE_TIME_TOKEN_TYPES = {
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
};

export const PORTAL_ONE_TIME_TOKEN_TYPE_VALUES = Object.values(PORTAL_ONE_TIME_TOKEN_TYPES);

export const PORTAL_SUGGESTER_ALLOW_LIST = [
  REFERENCE_TYPES.ALLERGY,
  REFERENCE_TYPES.CATCHMENT,
  REFERENCE_TYPES.DRUG,
  REFERENCE_TYPES.DIET,
  REFERENCE_TYPES.PROCEDURE_TYPE,
  REFERENCE_TYPES.IMAGING_TYPE,
  REFERENCE_TYPES.VILLAGE,
  REFERENCE_TYPES.ETHNICITY,
  REFERENCE_TYPES.NATIONALITY,
  REFERENCE_TYPES.COUNTRY,
  REFERENCE_TYPES.CONTACT_RELATIONSHIP,
  REFERENCE_TYPES.DIVISION,
  REFERENCE_TYPES.DIAGNOSIS,
  REFERENCE_TYPES.SUBDIVISION,
  REFERENCE_TYPES.MEDICAL_AREA,
  REFERENCE_TYPES.NURSING_ZONE,
  REFERENCE_TYPES.SETTLEMENT,
  REFERENCE_TYPES.OCCUPATION,
  REFERENCE_TYPES.PLACE_OF_BIRTH,
  REFERENCE_TYPES.RELIGION,
  REFERENCE_TYPES.REACTION,
  REFERENCE_TYPES.FAMILY_RELATION,
  REFERENCE_TYPES.PATIENT_BILLING_TYPE,
  REFERENCE_TYPES.REFERRAL_SOURCE,
  REFERENCE_TYPES.VACCINE_NOT_GIVEN_REASON,
  REFERENCE_TYPES.VACCINE_CIRCUMSTANCE,
  REFERENCE_TYPES.INSURER,
  OTHER_REFERENCE_TYPES.LAB_TEST_PANEL,
  OTHER_REFERENCE_TYPES.LAB_TEST_TYPE,
  OTHER_REFERENCE_TYPES.LOCATION_GROUP,
  OTHER_REFERENCE_TYPES.DEPARTMENT,
  OTHER_REFERENCE_TYPES.FACILITY,
  OTHER_REFERENCE_TYPES.LOCATION,
];
