import { GENERAL_IMPORTABLE_DATA_TYPES } from './importable';

const REFERENCE_TYPES_NOUNS = GENERAL_IMPORTABLE_DATA_TYPES.map(
  noun => String(noun).charAt(0).toUpperCase() + String(noun).slice(1),
);

export const PERMISSION_NOUNS = [
  ...REFERENCE_TYPES_NOUNS,
  'all',
  'Appointment',
  'Asset',
  'Attachment',
  'CertificateNotification',
  'Charting',
  'Discharge',
  'DocumentMetadata',
  'Encounter',
  'EncounterDiagnosis',
  'EncounterNote',
  'ImagingRequest',
  'Invoice',
  'InvoicePayment',
  'IPSRequest',
  'LabRequest',
  'LabRequestLog',
  'LabRequestStatus',
  'LabTest',
  'LabTestResult',
  'Medication',
  'MedicationAdministration',
  'MedicationPharmacyNote',
  'OtherPractitionerEncounterNote',
  'PatientAllergy',
  'PatientBirthData',
  'PatientCarePlan',
  'PatientCondition',
  'PatientDeath',
  'PatientDeathData',
  'PatientFamilyHistory',
  'PatientIssue',
  'PatientLetterTemplate',
  'PatientProgramRegistration',
  'PatientProgramRegistrationCondition',
  'PatientSecondaryId',
  'PatientVaccine',
  'Permission',
  'Procedure',
  'ReferenceData',
  'Referral',
  'Report',
  'ReportDbSchema',
  'ReportDefinition',
  'ReportDefinitionVersion',
  'ReportRequest',
  'Role',
  'SensitiveLabRequest',
  'Setting',
  'Signer',
  'StaticReport',
  'Tasking',
  'Template',
  'Translation',
  'TranslatedString',
  'TreatmentPlan',
  'TreatmentPlanNote',
  'Triage',
  'Vitals',
];

export const NOUNS_WITH_OBJECT_ID = [
  'SurveyResponse',
  'Survey',
  'StaticReport',
  'ReportDefinition',
  'ProgramRegistry',
];
