export const REFERENCE_DATA_RELATION_TYPES = {
  ADDRESS_HIERARCHY: 'address_hierarchy',
  FACILITY_CATCHMENT: 'facility_catchment',
  TASK: 'task',
  MEDICATION: 'medication',
};

export const DEFAULT_HIERARCHY_TYPE = REFERENCE_DATA_RELATION_TYPES.ADDRESS_HIERARCHY;

import { REFERENCE_TYPE_VALUES, OTHER_REFERENCE_TYPE_VALUES, SYSTEM_DATA_TYPES_VALUES } from './importable.ts';

export const MANAGEABLE_REFERENCE_DATA_TYPES = [
  ...REFERENCE_TYPE_VALUES,
  ...OTHER_REFERENCE_TYPE_VALUES,
  ...SYSTEM_DATA_TYPES_VALUES,
];

export const SEARCHABLE_COLUMN_TYPES = [
  'STRING',
  'TEXT',
  'CHAR',
  'VARCHAR',
  'INTEGER',
  'FLOAT',
  'DOUBLE',
  'DECIMAL',
  'REAL',
  'BOOLEAN',
] as const;
