import { NOTE_TYPES, NOTE_TYPE_LABELS } from './notes.js';

export const TEMPLATE_TYPES = {
  PATIENT_LETTER: 'patientLetter',
  TREATMENT_PLAN: NOTE_TYPES.TREATMENT_PLAN,
  DISCHARGE: NOTE_TYPES.DISCHARGE,
  HANDOVER: NOTE_TYPES.HANDOVER,
  OTHER: NOTE_TYPES.OTHER,
};

export const TEMPLATE_TYPE_LABELS = {
  [TEMPLATE_TYPES.PATIENT_LETTER]: 'Patient letter',
  [TEMPLATE_TYPES.TREATMENT_PLAN]: NOTE_TYPE_LABELS[NOTE_TYPES.TREATMENT_PLAN],
  [TEMPLATE_TYPES.DISCHARGE]: NOTE_TYPE_LABELS[NOTE_TYPES.DISCHARGE],
  [TEMPLATE_TYPES.OTHER]: NOTE_TYPE_LABELS[NOTE_TYPES.OTHER],
  [TEMPLATE_TYPES.HANDOVER]: NOTE_TYPE_LABELS[NOTE_TYPES.HANDOVER],
};
