import { PatientVaccineProps } from '../../interfaces/PatientVaccineProps';
import { VaccineStatus } from '../../helpers/constants';

export const vaccineHistoryList: PatientVaccineProps[] = [
  {
    header: 'Birth',
    bcg: VaccineStatus.TAKEN,
    hepb: null,
    dpt: null,
    pcv: null,
    ipv: null,
    mr: null,
    tt: null,
  },
  {
    header: '24hrs from birth',
    bcg: VaccineStatus.SCHEDULED,
    hepb: null,
    dpt: null,
    pcv: null,
    ipv: null,
    mr: null,
    tt: null,
  },
  {
    header: '6 weeks',
    bcg: VaccineStatus.NOT_TAKEN,
    hepb: null,
    dpt: VaccineStatus.SCHEDULED,
    pcv: VaccineStatus.SCHEDULED,
    ipv: VaccineStatus.SCHEDULED,
    mr: null,
    tt: null,
  },
  {
    header: '10 weeks',
    bcg: VaccineStatus.TAKEN_NOT_ON_TIME,
    hepb: null,
    dpt: VaccineStatus.TAKEN_NOT_ON_TIME,
    pcv: VaccineStatus.NOT_TAKEN,
    ipv: VaccineStatus.NOT_TAKEN,
    mr: null,
    tt: null,
  },
  {
    header: '14 weeks',
    bcg: null,
    hepb: null,
    dpt: null,
    pcv: null,
    ipv: null,
    mr: null,
    tt: null,
  },
  {
    header: '1 yrs',
    bcg: null,
    hepb: null,
    dpt: null,
    pcv: null,
    ipv: null,
    mr: null,
    tt: null,
  },
  {
    header: '6 yrs',
    bcg: null,
    hepb: null,
    dpt: null,
    pcv: null,
    ipv: null,
    mr: null,
    tt: null,
  },
];
