// Please keep in sync with:
// - @tamanu/constants/surveys.js
export const PATIENT_DATA_FIELD_LOCATIONS = {
  PatientProgramRegistration: {
    registrationClinicalStatus: 'clinicalStatusId',
    programRegistrationStatus: 'registrationStatus',
    registrationClinician: 'clinicianId',
    registeringFacility: 'registeringFacilityId',
    registrationCurrentlyAtVillage: 'villageId',
    registrationCurrentlyAtFacility: 'facilityId',
  },
  Patient: {
    firstName: 'firstName',
    middleName: 'middleName',
    lastName: 'lastName',
    culturalName: 'culturalName',
    dateOfBirth: 'dateOfBirth',
    dateOfDeath: 'dateOfDeath',
    sex: 'sex',
    email: 'email',

    villageId: 'villageId',
  },
  PatientAdditionalData: {
    placeOfBirth: 'placeOfBirth',
    bloodType: 'bloodType',
    primaryContactNumber: 'primaryContactNumber',
    secondaryContactNumber: 'secondaryContactNumber',
    maritalStatus: 'maritalStatus',
    cityTown: 'cityTown',
    streetVillage: 'streetVillage',
    educationalLevel: 'educationalLevel',
    socialMedia: 'socialMedia',
    title: 'title',
    birthCertificate: 'birthCertificate',
    drivingLicense: 'drivingLicense',
    passport: 'passport',
    emergencyContactName: 'emergencyContactName',
    emergencyContactNumber: 'emergencyContactNumber',

    registeredById: 'registeredById',
    motherId: 'motherId',
    fatherId: 'fatherId',
    nationalityId: 'nationalityId',
    countryId: 'countryId',
    divisionId: 'divisionId',
    subdivisionId: 'subdivisionId',
    medicalAreaId: 'medicalAreaId',
    nursingZoneId: 'nursingZoneId',
    settlementId: 'settlementId',
    ethnicityId: 'ethnicityId',
    occupationId: 'occupationId',
    religionId: 'religionId',
    patientBillingTypeId: 'patientBillingTypeId',
    countryOfBirthId: 'countryOfBirthId',
  },
};
