
select
  p.first_name,
  p.last_name,
  to_char(p.date_of_birth::date, 'yyyy-mm-dd') as dob,
  p.sex,
  p.display_id as patient_id,
  rd.name as village,
  to_char(sr.end_time::date, 'yyyy-mm-dd') endtime,
  max(case when sra.data_element_id = 'pde-samkapSUR07' then sra.body end) as	"samkapSUR07: Tobacco products contain chemicals that are known to cause cancer",
  max(case when sra.data_element_id = 'pde-samkapSUR08' then sra.body end) as	"samkapSUR08: Quitting is the best action tobacco users can take to improve their health",
  max(case when sra.data_element_id = 'pde-samkapSUR09' then sra.body end) as	"samkapSUR09: Quitting tobacco has short-term and long-term health benefits",
  max(case when sra.data_element_id = 'pde-samkapSUR10' then sra.body end) as	"samkapSUR10: There are financial and social benefits to quitting tobacco use",
  max(case when sra.data_element_id = 'pde-samkapSUR11' then sra.body end) as	"samkapSUR11: Smoking affects your lungs and heart",
  max(case when sra.data_element_id = 'pde-samkapSUR12' then sra.body end) as	"samkapSUR12: Where did you get the answers to the above questions?",
  max(case when sra.data_element_id = 'pde-samkapSUR13' then sra.body end) as	"samkapSUR13: If other, please specify:",
  max(case when sra.data_element_id = 'pde-samkapSUR15' then sra.body end) as	"samkapSUR15: How much do you know about the health effects of alcohol use (0 is nothing at all / 10 is quite familiar with it)?",
  max(case when sra.data_element_id = 'pde-samkapSUR17' then sra.body end) as	"samkapSUR17: Harmful use of alcohol is a risk factor for cardiovascular disease",
  max(case when sra.data_element_id = 'pde-samkapSUR18' then sra.body end) as	"samkapSUR18: Harmful use of alcohol includes high levels of consumption each day, as well as single or repeated episodes of drinking to intoxication (binge drinking)",
  max(case when sra.data_element_id = 'pde-samkapSUR19' then sra.body end) as	"samkapSUR19: The pattern of drinking and the amount and quality of alcohol consumed all contribute to the risk related to alcohol consumption",
  max(case when sra.data_element_id = 'pde-samkapSUR20' then sra.body end) as	"samkapSUR20: Medium levels of alcohol use are not associated with increased risk",
  max(case when sra.data_element_id = 'pde-samkapSUR21' then sra.body end) as	"samkapSUR21: Lower risk alcohol consumption is considered to be no more than 2 alcoholic drinks per day and not drinking on at least 2 days of the week",
  max(case when sra.data_element_id = 'pde-samkapSUR22' then sra.body end) as	"samkapSUR22: Where did you get the answers to the above questions?",
  max(case when sra.data_element_id = 'pde-samkapSUR23' then sra.body end) as	"samkapSUR23: If other, please specify:",
  max(case when sra.data_element_id = 'pde-samkapSUR25' then sra.body end) as	"samkapSUR25: How much do you know about the health effects of diet (0 is nothing at all / 10 is quite familiar with it)?",
  max(case when sra.data_element_id = 'pde-samkapSUR27' then sra.body end) as	"samkapSUR27: Unhealthy eating habits can result in a range of health conditions such as cancer, diabetes and micronutrient deficiencies",
  max(case when sra.data_element_id = 'pde-samkapSUR28' then sra.body end) as	"samkapSUR28: An unhealthy diet is characterized by low intake of fruit and vegetables",
  max(case when sra.data_element_id = 'pde-samkapSUR29' then sra.body end) as	"samkapSUR29: An unhealthy diet is characterized by high intakes of salt, fats and sugars",
  max(case when sra.data_element_id = 'pde-samkapSUR30' then sra.body end) as	"samkapSUR30: Risk for cardiovascular disease is increased by an unhealthy diet",
  max(case when sra.data_element_id = 'pde-samkapSUR31' then sra.body end) as	"samkapSUR31: Unhealthy diet contributes to overweight and obesity",
  max(case when sra.data_element_id = 'pde-samkapSUR32' then sra.body end) as	"samkapSUR32: Being obese or overweight is a risk factor for cardiovascular disease",
  max(case when sra.data_element_id = 'pde-samkapSUR33' then sra.body end) as	"samkapSUR33: Select all of the following that are part of a healthy diet:",
  max(case when sra.data_element_id = 'pde-samkapSUR35' then sra.body end) as	"samkapSUR35: Fruits",
  max(case when sra.data_element_id = 'pde-samkapSUR36' then sra.body end) as	"samkapSUR36: Food and drinks with added sugar",
  max(case when sra.data_element_id = 'pde-samkapSUR37' then sra.body end) as	"samkapSUR37: Vegetables",
  max(case when sra.data_element_id = 'pde-samkapSUR38' then sra.body end) as	"samkapSUR38: Fatty foods",
  max(case when sra.data_element_id = 'pde-samkapSUR39' then sra.body end) as	"samkapSUR39: Processed red meat",
  max(case when sra.data_element_id = 'pde-samkapSUR40' then sra.body end) as	"samkapSUR40: Whole grains",
  max(case when sra.data_element_id = 'pde-samkapSUR41' then sra.body end) as	"samkapSUR41: Salty foods",
  max(case when sra.data_element_id = 'pde-samkapSUR42' then sra.body end) as	"samkapSUR42: Water",
  max(case when sra.data_element_id = 'pde-samkapSUR43' then sra.body end) as	"samkapSUR43: Where did you get the answers to the above questions?",
  max(case when sra.data_element_id = 'pde-samkapSUR44' then sra.body end) as	"samkapSUR44: If other, please specify:",
  max(case when sra.data_element_id = 'pde-samkapSUR46' then sra.body end) as	"samkapSUR46: How much do you know about the health effects of physical activity (0 is nothing at all / 10 is quite familiar with it)?",
  max(case when sra.data_element_id = 'pde-samkapSUR48' then sra.body end) as	"samkapSUR48: Insufficient physical activity is a key risk factor for cardiovascular disease, cancer and diabetes",
  max(case when sra.data_element_id = 'pde-samkapSUR49' then sra.body end) as	"samkapSUR49: Insufficient physical activity is one of the leading risk factors for early death",
  max(case when sra.data_element_id = 'pde-samkapSUR50' then sra.body end) as	"samkapSUR50: Regular and adequate levels of physical activity reduce the risk of hypertension, heart attack, stroke, diabetes, various types of cancer, and depression",
  max(case when sra.data_element_id = 'pde-samkapSUR51' then sra.body end) as	"samkapSUR51: Quality of physical activity depends on the frequency, duration and type of activity",
  max(case when sra.data_element_id = 'pde-samkapSUR52' then sra.body end) as	"samkapSUR52: Only moderate or high intensity physical activity is good for health.",
  max(case when sra.data_element_id = 'pde-samkapSUR53' then sra.body end) as	"samkapSUR53: Adults should perform at least 150 minutes of moderate intensity physical activity or 75 minutes of high intensity physical activity (or equivalent), spread throughout the week",
  max(case when sra.data_element_id = 'pde-samkapSUR54' then sra.body end) as	"samkapSUR54: Increasing the amount of physical activity can lead to additional health benefits",
  max(case when sra.data_element_id = 'pde-samkapSUR55' then sra.body end) as	"samkapSUR55: Where did you get the answers to the above questions?",
  max(case when sra.data_element_id = 'pde-samkapSUR56' then sra.body end) as	"samkapSUR56: If other, please specify:",
  max(case when sra.data_element_id = 'pde-samkapSUR58' then sra.body end) as	"samkapSUR58: How much do you know about hypertension (high blood pressure) (0 is nothing at all / 10 is quite familiar with it)?",
  max(case when sra.data_element_id = 'pde-samkapSUR60' then sra.body end) as	"samkapSUR60: Measuring blood pressure is the only way to diagnose hypertension",
  max(case when sra.data_element_id = 'pde-samkapSUR61' then sra.body end) as	"samkapSUR61: It is not necessary to check your blood pressure periodically",
  max(case when sra.data_element_id = 'pde-samkapSUR62' then sra.body end) as	"samkapSUR62: Blood pressure measurement and control is especially important in adults who have had a prior heart attack or stroke or have a family history of heart attack or stroke",
  max(case when sra.data_element_id = 'pde-samkapSUR63' then sra.body end) as	"samkapSUR63: Blood pressure measurement and control is especially important in adults who have diabetes",
  max(case when sra.data_element_id = 'pde-samkapSUR64' then sra.body end) as	"samkapSUR64: Blood pressure measurement and control is especially important in adults who have chronic kidney disease (CKD)",
  max(case when sra.data_element_id = 'pde-samkapSUR65' then sra.body end) as	"samkapSUR65: Blood pressure measurement and control is especially important in adults who are obese",
  max(case when sra.data_element_id = 'pde-samkapSUR66' then sra.body end) as	"samkapSUR66: Blood pressure measurement and control is especially important in adults who use tobacco",
  max(case when sra.data_element_id = 'pde-samkapSUR67' then sra.body end) as	"samkapSUR67: High blood pressure (hypertension) is a risk factor for cardio vascular disease",
  max(case when sra.data_element_id = 'pde-samkapSUR82' then sra.body end) as	"samkapSUR82: How much do you know about heart disease (0 is nothing at all / 10 is quite familiar with it)?",
  max(case when sra.data_element_id = 'pde-samkapSUR68' then sra.body end) as	"samkapSUR68: Where did you get the answers to the above questions?",
  max(case when sra.data_element_id = 'pde-samkapSUR69' then sra.body end) as	"samkapSUR69: If other, please specify:",
  max(case when sra.data_element_id = 'pde-samkapSUR71' then sra.body end) as	"samkapSUR71: How much do you know about diabetes (0 is nothing at all / 10 is quite familiar with it)?",
  max(case when sra.data_element_id = 'pde-samkapSUR73' then sra.body end) as	"samkapSUR73: Improve diet",
  max(case when sra.data_element_id = 'pde-samkapSUR74' then sra.body end) as	"samkapSUR74: Take medications",
  max(case when sra.data_element_id = 'pde-samkapSUR75' then sra.body end) as	"samkapSUR75: Do more exercise/physical activity",
  max(case when sra.data_element_id = 'pde-samkapSUR76' then sra.body end) as	"samkapSUR76: Quit smoking",
  max(case when sra.data_element_id = 'pde-samkapSUR77' then sra.body end) as	"samkapSUR77: Nothing",
  max(case when sra.data_element_id = 'pde-samkapSUR78' then sra.body end) as	"samkapSUR78: Reduce weight",
  max(case when sra.data_element_id = 'pde-samkapSUR79' then sra.body end) as	"samkapSUR79: Where did you get the answers to the above questions?",
  max(case when sra.data_element_id = 'pde-samkapSUR80' then sra.body end) as	"samkapSUR80: If other, please specify:",
  max(case when sra.data_element_id = 'pde-samkapSUR83' then sra.body end) as	"samkapSUR83: If you know something about heart disease, do you agree that it can be prevented?",
  max(case when sra.data_element_id = 'pde-samkapSUR84' then sra.body end) as	"samkapSUR84: Where did you get the answers to the above questions?",
  max(case when sra.data_element_id = 'pde-samkapSUR85' then sra.body end) as	"samkapSUR85: If other, please specify:",
  max(case when sra.data_element_id = 'pde-samkapSUR87' then sra.body end) as	"samkapSUR87: How much do you know about stroke (0 is nothing at all / 10 is quite familiar with it)?",
  max(case when sra.data_element_id = 'pde-samkapSUR89' then sra.body end) as	"samkapSUR89: Where did you get the answers to the above questions?",
  max(case when sra.data_element_id = 'pde-samkapSUR90' then sra.body end) as	"samkapSUR90: If other, please specify:",
  max(case when sra.data_element_id = 'pde-samkapSUR01' then sra.body end) as	"samkapSUR01: Screening date",
  max(case when sra.data_element_id = 'pde-samkapSUR03' then sra.body end) as	"samkapSUR03: How much do you know about the health effects of smoking (0 is nothing at all / 10 is quite familiar with it)?",
  max(case when sra.data_element_id = 'pde-samkapSUR05' then sra.body end) as	"samkapSUR05: All tobacco products are harmful",
  max(case when sra.data_element_id = 'pde-samkapSUR06' then sra.body end) as	"samkapSUR06: Smoke from tobacco products (second-hand smoke) is not harmful to health",
  max(case when sra.data_element_id = 'pde-samkapSUR88' then sra.body end) as	"samkapSUR88: If you know something about strokes, do you agree that people with high blood pressure are more likely to have a stroke?"
from survey_response_answers sra 
left join survey_responses sr on sr.id = sra.response_id 
left join encounters e on e.id = sr.encounter_id
left join patients p on p.id = e.patient_id
left join patient_additional_data pad2 on pad2.patient_id = p.id
left join reference_data rd on rd.id = p.village_id
left join reference_data rd1 on rd1.id = pad2.nationality_id
where sr.survey_id  = 'program-samoancdscreening-sampenkapsur'
group by sr.end_time, sr.encounter_id, p.first_name, p.last_name, p.date_of_birth, p.sex, p.display_id, village