name: CD Setup
description: Set up Pulumi, Tailscale, and K8S
inputs:
  ops-ssh-key:
    description: SSH key for ops repo
    required: false
  ops-ref:
    description: Ref to checkout in ops repo
    default: main
runs:
  using: composite
  steps:
    - if: inputs.ops-ssh-key
      name: Checkout ops
      uses: actions/checkout@v5
      with:
        repository: beyondessential/ops
        ssh-key: ${{ inputs.ops-ssh-key }}
        path: ops
        ref: ${{ inputs.ops-ref }}
    - name: Remove ops/.git so pulumi doesn't get confused
      if: inputs.ops-ssh-key
      shell: bash
      run: rm -rf ops/.git

    - name: Install Node.js for ops
      if: inputs.ops-ssh-key
      uses: actions/setup-node@v5
      with:
        node-version-file: ops/.node-version
        cache: npm

    - name: Install Node.js for us
      if: '!inputs.ops-ssh-key'
      uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        cache: npm

    - name: Prepare pulumi
      if: inputs.ops-ssh-key
      shell: bash
      working-directory: ops/pulumi
      run: npm ci

    - name: Pre-install pulumi
      if: inputs.ops-ssh-key
      uses: pulumi/actions@v5

    - name: Connect to Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ vars.TS_OAUTH_CLIENT_ID }}
        audience: api.tailscale.com/${{ vars.TS_OAUTH_CLIENT_ID }}
        tags: ${{ vars.TS_TAGS }} # must be synced to actual OIDC trust in Tailscale

    - name: Configure kubeconfig
      shell: bash
      run: tailscale configure kubeconfig ${{ vars.TS_K8S_OPERATOR_HOSTNAME }}

    - name: Test kubernetes cluster for readiness
      shell: bash
      run: kubectl get namespace/tamanu-system
