export { LocationAdminView } from './LocationAdminView';
export { AssetUploaderView } from './AssetUploaderView';
export { UserAdminView } from './UserAdminView';
export { ProgramsAdminView } from './ProgramsAdminView';
export { PermissionsAdminView } from './PermissionsAdminView';
export { ReferenceDataAdminView, ClinicalDataAdminView, UserDataAdminView } from './ReferenceDataAdminView';
export { PatientMergeView } from './patientMerge';
export { SyncView } from './SyncView';
export { ReportsAdminView } from './reports/ReportsAdminView';
export { TemplateView } from './templates';
