export const mapToSuggestions = objects =>
  objects.map(({ id, name }) => ({ label: name, value: id }));

export function createDummySuggester(options) {
  return {
    fetchSuggestions: search => {
      const filter = ({ label }) => label.toLowerCase().includes(search.toLowerCase());
      return options.filter(filter).slice(0, 20);
    },
    fetchCurrentOption: value => options.find(s => s.value === value),
  };
}

export function getDummySurvey() {
  return {
    id: 'program-cdscreening-cdhivscreeningform',
    name: '(Demo) HIV Risk Screening Form',
    surveyType: 'programs',
    createdAt: '2022-01-20T22:51:25.942Z',
    updatedAt: '2022-01-23T21:56:27.592Z',
    programId: 'program-cdscreening',
    components: [
      {
        id: 'program-cdscreening-cdhivscreeningform-HIVRiskScreen1',
        screenIndex: 0,
        componentIndex: 0,
        text: '',
        visibilityCriteria: '',
        validationCriteria: '',
        detail: '',
        config: '',
        calculation: '',
        createdAt: '2022-01-20T22:51:32.563Z',
        updatedAt: '2022-01-23T21:56:31.875Z',
        surveyId: 'program-cdscreening-cdhivscreeningform',
        dataElementId: 'pde-HIVRiskScreen1',
        dataElement: {
          id: 'pde-HIVRiskScreen1',
          code: 'HIVRiskScreen1',
          name: 'Section1: Screening Information',
          indicator: null,
          defaultText: 'Section1: Screening Information',
          type: 'Instruction',
          createdAt: '2022-01-20T22:51:28.485Z',
          updatedAt: '2022-01-23T21:56:28.928Z',
          defaultOptions: null,
        },
        options: null,
      },
      {
        id: 'program-cdscreening-cdhivscreeningform-HIVRiskScreen10',
        screenIndex: 1,
        componentIndex: 5,
        text: '',
        visibilityCriteria: '',
        validationCriteria: '',
        detail: '',
        config: '',
        calculation: '',
        createdAt: '2022-01-20T22:51:32.563Z',
        updatedAt: '2022-01-23T21:56:31.875Z',
        surveyId: 'program-cdscreening-cdhivscreeningform',
        dataElementId: 'pde-HIVRiskScreen10',
        dataElement: {
          id: 'pde-HIVRiskScreen10',
          code: 'HIVRiskScreen10',
          name: 'Individual has shared needles or injecting equipment with other individuals',
          indicator: null,
          defaultText:
            'Have you ever shared needles or injecting equipment with other individuals including your spouse or significant other?',
          type: 'Radio',
          createdAt: '2022-01-20T22:51:28.485Z',
          updatedAt: '2022-01-23T21:56:28.928Z',
          defaultOptions: { Yes: 'Yes', No: 'No' },
        },
        options: null,
      },
      {
        id: 'program-cdscreening-cdhivscreeningform-HIVRiskScreen11',
        screenIndex: 1,
        componentIndex: 6,
        text: '',
        visibilityCriteria: '',
        validationCriteria: '',
        detail: '',
        config: '',
        calculation: '',
        createdAt: '2022-01-20T22:51:32.563Z',
        updatedAt: '2022-01-23T21:56:31.875Z',
        surveyId: 'program-cdscreening-cdhivscreeningform',
        dataElementId: 'pde-HIVRiskScreen11',
        dataElement: {
          id: 'pde-HIVRiskScreen11',
          code: 'HIVRiskScreen11',
          name: 'Individual has experienced symptoms and/or signs of an STI',
          indicator: null,
          defaultText:
            'Have you experienced any symptoms and/or signs of an STI, such as vaginal/urethral discharge or genital sores?',
          type: 'Radio',
          createdAt: '2022-01-20T22:51:28.485Z',
          updatedAt: '2022-01-23T21:56:28.928Z',
          defaultOptions: { Yes: 'Yes', No: 'No' },
        },
        options: null,
      },
      {
        id: 'program-cdscreening-cdhivscreeningform-HIVRiskScreen12',
        screenIndex: 2,
        componentIndex: 0,
        text: '',
        visibilityCriteria: '',
        validationCriteria: '',
        detail: '',
        config: '',
        calculation: '',
        createdAt: '2022-01-20T22:51:32.563Z',
        updatedAt: '2022-01-23T21:56:31.875Z',
        surveyId: 'program-cdscreening-cdhivscreeningform',
        dataElementId: 'pde-HIVRiskScreen12',
        dataElement: {
          id: 'pde-HIVRiskScreen12',
          code: 'HIVRiskScreen12',
          name: 'Section 3: Rapid HIV Test',
          indicator: null,
          defaultText: 'Section 3: Rapid HIV Test',
          type: 'Instruction',
          createdAt: '2022-01-20T22:51:28.485Z',
          updatedAt: '2022-01-23T21:56:28.928Z',
          defaultOptions: null,
        },
        options: null,
      },
      {
        id: 'program-cdscreening-cdhivscreeningform-HIVRiskScreen13',
        screenIndex: 2,
        componentIndex: 1,
        text: '',
        visibilityCriteria: '',
        validationCriteria: '',
        detail: '',
        config: '',
        calculation: '',
        createdAt: '2022-01-20T22:51:32.563Z',
        updatedAt: '2022-01-23T21:56:31.875Z',
        surveyId: 'program-cdscreening-cdhivscreeningform',
        dataElementId: 'pde-HIVRiskScreen13',
        dataElement: {
          id: 'pde-HIVRiskScreen13',
          code: 'HIVRiskScreen13',
          name: 'Rapid HIV test conducted',
          indicator: null,
          defaultText: 'Have you conducted a rapid HIV test for this individual?',
          type: 'Radio',
          createdAt: '2022-01-20T22:51:28.485Z',
          updatedAt: '2022-01-23T21:56:28.928Z',
          defaultOptions: { Yes: 'Yes', No: 'No' },
        },
        options: null,
      },
      {
        id: 'program-cdscreening-cdhivscreeningform-HIVRiskScreen14',
        screenIndex: 2,
        componentIndex: 2,
        text: '',
        visibilityCriteria: '{"HIVRiskScreen13": "Yes"}',
        validationCriteria: '',
        detail: '',
        config: '',
        calculation: '',
        createdAt: '2022-01-20T22:51:32.563Z',
        updatedAt: '2022-01-23T21:56:31.875Z',
        surveyId: 'program-cdscreening-cdhivscreeningform',
        dataElementId: 'pde-HIVRiskScreen14',
        dataElement: {
          id: 'pde-HIVRiskScreen14',
          code: 'HIVRiskScreen14',
          name: 'Date rapid HIV test conducted',
          indicator: null,
          defaultText: 'Date rapid HIV test conducted',
          type: 'Date',
          createdAt: '2022-01-20T22:51:28.485Z',
          updatedAt: '2022-01-23T21:56:28.928Z',
          defaultOptions: null,
        },
        options: null,
      },
      {
        id: 'program-cdscreening-cdhivscreeningform-HIVRiskScreen15',
        screenIndex: 2,
        componentIndex: 3,
        text: '',
        visibilityCriteria: '{"HIVRiskScreen13": "Yes"}',
        validationCriteria: '',
        detail: '',
        config: '',
        calculation: '',
        createdAt: '2022-01-20T22:51:32.563Z',
        updatedAt: '2022-01-23T21:56:31.875Z',
        surveyId: 'program-cdscreening-cdhivscreeningform',
        dataElementId: 'pde-HIVRiskScreen15',
        dataElement: {
          id: 'pde-HIVRiskScreen15',
          code: 'HIVRiskScreen15',
          name: 'Rapid HIV test result',
          indicator: null,
          defaultText: 'Rapid HIV test result',
          type: 'Radio',
          createdAt: '2022-01-20T22:51:28.485Z',
          updatedAt: '2022-01-23T21:56:28.928Z',
          defaultOptions: { Positive: 'Positive', Negative: 'Negative', Invalid: 'Invalid' },
        },
        options: null,
      },
      {
        id: 'program-cdscreening-cdhivscreeningform-HIVRiskScreen2',
        screenIndex: 0,
        componentIndex: 1,
        text: '',
        visibilityCriteria: '',
        validationCriteria: '',
        detail: '',
        config: '',
        calculation: '',
        createdAt: '2022-01-20T22:51:32.563Z',
        updatedAt: '2022-01-23T21:56:31.875Z',
        surveyId: 'program-cdscreening-cdhivscreeningform',
        dataElementId: 'pde-HIVRiskScreen2',
        dataElement: {
          id: 'pde-HIVRiskScreen2',
          code: 'HIVRiskScreen2',
          name: 'Screening date',
          indicator: null,
          defaultText: 'Screening date',
          type: 'SubmissionDate',
          createdAt: '2022-01-20T22:51:28.485Z',
          updatedAt: '2022-01-23T21:56:28.928Z',
          defaultOptions: null,
        },
        options: null,
      },
      {
        id: 'program-cdscreening-cdhivscreeningform-HIVRiskScreen3',
        screenIndex: 0,
        componentIndex: 2,
        text: '',
        visibilityCriteria: '',
        validationCriteria: '',
        detail: '',
        config: '',
        calculation: '',
        createdAt: '2022-01-20T22:51:32.563Z',
        updatedAt: '2022-01-23T21:56:31.875Z',
        surveyId: 'program-cdscreening-cdhivscreeningform',
        dataElementId: 'pde-HIVRiskScreen3',
        dataElement: {
          id: 'pde-HIVRiskScreen3',
          code: 'HIVRiskScreen3',
          name: 'Name of person who conducted the screening',
          indicator: null,
          defaultText: 'Name of person conducting the screening',
          type: 'UserData',
          createdAt: '2022-01-20T22:51:28.485Z',
          updatedAt: '2022-01-23T21:56:28.928Z',
          defaultOptions: null,
        },
        options: null,
      },
      {
        id: 'program-cdscreening-cdhivscreeningform-HIVRiskScreen4',
        screenIndex: 0,
        componentIndex: 3,
        text: '',
        visibilityCriteria: '',
        validationCriteria: '',
        detail: '',
        config: '',
        calculation: '',
        createdAt: '2022-01-20T22:51:32.563Z',
        updatedAt: '2022-01-23T21:56:31.875Z',
        surveyId: 'program-cdscreening-cdhivscreeningform',
        dataElementId: 'pde-HIVRiskScreen4',
        dataElement: {
          id: 'pde-HIVRiskScreen4',
          code: 'HIVRiskScreen4',
          name:
            'Individual counselled on the purpose of screening and gave informed consent to conduct the screen',
          indicator: null,
          defaultText:
            'Has the individual been counselled on the purpose of screening and given informed consent to conduct the screen?',
          type: 'Radio',
          createdAt: '2022-01-20T22:51:28.485Z',
          updatedAt: '2022-01-23T21:56:28.928Z',
          defaultOptions: { Yes: 'Yes', No: 'No' },
        },
        options: null,
      },
      {
        id: 'program-cdscreening-cdhivscreeningform-HIVRiskScreen5',
        screenIndex: 1,
        componentIndex: 0,
        text: '',
        visibilityCriteria: '',
        validationCriteria: '',
        detail: '',
        config: '',
        calculation: '',
        createdAt: '2022-01-20T22:51:32.563Z',
        updatedAt: '2022-01-23T21:56:31.875Z',
        surveyId: 'program-cdscreening-cdhivscreeningform',
        dataElementId: 'pde-HIVRiskScreen5',
        dataElement: {
          id: 'pde-HIVRiskScreen5',
          code: 'HIVRiskScreen5',
          name: 'Section 2: Risk Screen',
          indicator: null,
          defaultText: 'Section 2: Risk Screen',
          type: 'Instruction',
          createdAt: '2022-01-20T22:51:28.485Z',
          updatedAt: '2022-01-23T21:56:28.928Z',
          defaultOptions: null,
        },
        options: null,
      },
      {
        id: 'program-cdscreening-cdhivscreeningform-HIVRiskScreen6',
        screenIndex: 1,
        componentIndex: 1,
        text: '',
        visibilityCriteria: '',
        validationCriteria: '',
        detail: '',
        config: '',
        calculation: '',
        createdAt: '2022-01-20T22:51:32.563Z',
        updatedAt: '2022-01-23T21:56:31.876Z',
        surveyId: 'program-cdscreening-cdhivscreeningform',
        dataElementId: 'pde-HIVRiskScreen6',
        dataElement: {
          id: 'pde-HIVRiskScreen6',
          code: 'HIVRiskScreen6',
          name: 'Individual previously tested for HIV',
          indicator: null,
          defaultText: 'Have you been tested for HIV before?',
          type: 'Radio',
          createdAt: '2022-01-20T22:51:28.485Z',
          updatedAt: '2022-01-23T21:56:28.929Z',
          defaultOptions: { Yes: 'Yes', No: 'No' },
        },
        options: null,
      },
      {
        id: 'program-cdscreening-cdhivscreeningform-HIVRiskScreen7',
        screenIndex: 1,
        componentIndex: 2,
        text: '',
        visibilityCriteria: '{"HIVRiskScreen6": "Yes"}',
        validationCriteria: '',
        detail: '',
        config: '',
        calculation: '',
        createdAt: '2022-01-20T22:51:32.563Z',
        updatedAt: '2022-01-23T21:56:31.876Z',
        surveyId: 'program-cdscreening-cdhivscreeningform',
        dataElementId: 'pde-HIVRiskScreen7',
        dataElement: {
          id: 'pde-HIVRiskScreen7',
          code: 'HIVRiskScreen7',
          name: 'Date of last HIV test',
          indicator: null,
          defaultText: 'If Yes, when were you last tested? ',
          type: 'Date',
          createdAt: '2022-01-20T22:51:28.485Z',
          updatedAt: '2022-01-23T21:56:28.929Z',
          defaultOptions: { Yes: 'Yes', No: 'No' },
        },
        options: null,
      },
      {
        id: 'program-cdscreening-cdhivscreeningform-HIVRiskScreen8',
        screenIndex: 1,
        componentIndex: 3,
        text: '',
        visibilityCriteria: '{"HIVRiskScreen6": "Yes"}',
        validationCriteria: '',
        detail: '',
        config: '',
        calculation: '',
        createdAt: '2022-01-20T22:51:32.563Z',
        updatedAt: '2022-01-23T21:56:31.876Z',
        surveyId: 'program-cdscreening-cdhivscreeningform',
        dataElementId: 'pde-HIVRiskScreen8',
        dataElement: {
          id: 'pde-HIVRiskScreen8',
          code: 'HIVRiskScreen8',
          name: 'Last HIV test result',
          indicator: null,
          defaultText: 'If Yes, what was your test result?',
          type: 'Radio',
          createdAt: '2022-01-20T22:51:28.485Z',
          updatedAt: '2022-01-23T21:56:28.929Z',
          defaultOptions: { Positive: 'Positive', Negative: 'Negative', Unsure: 'Unsure' },
        },
        options: null,
      },
      {
        id: 'program-cdscreening-cdhivscreeningform-HIVRiskScreen9',
        screenIndex: 1,
        componentIndex: 4,
        text: '',
        visibilityCriteria: '',
        validationCriteria: '',
        detail: '',
        config: '',
        calculation: '',
        createdAt: '2022-01-20T22:51:32.563Z',
        updatedAt: '2022-01-23T21:56:31.876Z',
        surveyId: 'program-cdscreening-cdhivscreeningform',
        dataElementId: 'pde-HIVRiskScreen9',
        dataElement: {
          id: 'pde-HIVRiskScreen9',
          code: 'HIVRiskScreen9',
          name:
            "Individual has had sex without a condom with someone whose HIV status they didn't know, or who they knew was HIV-positive",
          indicator: null,
          defaultText:
            "Have you had sex without a condom with someone whose HIV status you didn't know, or who you knew was HIV-positive?",
          type: 'Radio',
          createdAt: '2022-01-20T22:51:28.485Z',
          updatedAt: '2022-01-23T21:56:28.929Z',
          defaultOptions: { Yes: 'Yes', No: 'No' },
        },
        options: null,
      },
    ],
  };
}
