import { MigrationInterface, QueryRunner, Table, TableColumn, TableForeignKey } from 'typeorm';

const TABLE_NAME = 'medication_administration_records';

const BaseColumns = [
  new TableColumn({
    name: 'id',
    type: 'varchar',
    isPrimary: true,
  }),
  new TableColumn({
    name: 'createdAt',
    type: 'datetime',
    default: "datetime('now')",
  }),
  new TableColumn({
    name: 'updatedAt',
    type: 'datetime',
    default: "datetime('now')",
  }),
  new TableColumn({
    name: 'deletedAt',
    type: 'datetime',
    default: null,
    isNullable: true,
  }),
  new TableColumn({
    name: 'updatedAtSyncTick',
    type: 'bigint',
    isNullable: false,
    default: -999,
  }),
];

const MedicationAdministrationRecordTable = new Table({
  name: TABLE_NAME,
  columns: [
    ...BaseColumns,
    new TableColumn({
      name: 'status',
      type: 'varchar',
      isNullable: true,
    }),
    new TableColumn({
      name: 'dueAt',
      type: 'string',
      isNullable: false,
    }),
    new TableColumn({
      name: 'recordedAt',
      type: 'string',
      isNullable: true,
    }),
    new TableColumn({
      name: 'recordedByUserId',
      type: 'varchar',
      isNullable: true,
    }),
    new TableColumn({
      name: 'isAutoGenerated',
      type: 'boolean',
      isNullable: false,
      default: false,
    }),
    new TableColumn({
      name: 'prescriptionId',
      type: 'varchar',
      isNullable: true,
    }),
    new TableColumn({
      name: 'changingStatusReason',
      type: 'text',
      isNullable: true,
    }),
    new TableColumn({
      name: 'reasonNotGivenId',
      type: 'varchar',
      isNullable: true,
    }),
    new TableColumn({
      name: 'changingNotGivenInfoReason',
      type: 'varchar',
      isNullable: true,
    }),
    new TableColumn({
      name: 'isEdited',
      type: 'boolean',
      isNullable: false,
      default: false,
    }),
    new TableColumn({
      name: 'isError',
      type: 'boolean',
      isNullable: true,
    }),
    new TableColumn({
      name: 'errorNotes',
      type: 'text',
      isNullable: true,
    }),
  ],
  foreignKeys: [
    new TableForeignKey({
      columnNames: ['prescriptionId'],
      referencedTableName: 'prescriptions',
      referencedColumnNames: ['id'],
    }),
    new TableForeignKey({
      columnNames: ['reasonNotGivenId'],
      referencedTableName: 'reference_data',
      referencedColumnNames: ['id'],
    }),
    new TableForeignKey({
      columnNames: ['recordedByUserId'],
      referencedTableName: 'users',
      referencedColumnNames: ['id'],
    }),
  ],
});

export class addMedicationAdministrationRecordTable1750787001000 implements MigrationInterface {
  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.createTable(MedicationAdministrationRecordTable, true);
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropTable(TABLE_NAME, true);
  }
}
