import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * 2.63–2.64 periodically ran approximate ANALYZEs; 2.65 replaces it with `PRAGMA optimize`. Discard
 * the query planner statistics from the any ANALYZEs which may have run, as stale stats may cause
 * `PRAGMA optimize`’s heuristics never to see any reason to replace them.
 */
export class resetQueryPlannerStats1789608077000 implements MigrationInterface {
  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE IF EXISTS sqlite_stat1');
  }

  /** Nothing to restore: statistics are regenerated by `PRAGMA optimize` */
  async down(): Promise<void> {}
}
