// This file is autogenerated, do not edit it directly
import { databaseSetup1661160427226 } from './1661160427226-databaseSetup';
import { updatePatientDateTimeColumns1661717539000 } from './1661717539000-updatePatientDateTimeColumns';
import { updateLabTestDate1662006885000 } from './1662006885000-updateLabTestDate';
import { updatePatientIssueDate1663564207000 } from './1663564207000-updatePatientIssueDate';
import { updatePatientEncounterDateTimeColumns1664229842000 } from './1664229842000-updatePatientEncounterDateTimeColumns';
import { alterModelsForV2Sync1663710579000 } from './1663710579000-alterModelsForV2Sync';
import { updateSurveyResponseDateTimeColumns1664475769000 } from './1664475769000-updateSurveyResponseDateTimeColumns';
import { changeCaseOfSpo21665717114000 } from './1665717114000-changeCaseOfSpo2';
import { updateLabRequestDateColumns1666171050000 } from './1666171050000-updateLabRequestDateColumns';
import { addFieldUpdateTicksToPAD1668987530000 } from './1668987530000-addFieldUpdateTicksToPAD';
import { addDefaultLastSuccessfulSyncPull1669160460000 } from './1669160460000-addDefaultLastSuccessfulSyncPull';
import { resyncPatientAdditionalData1669855692000 } from './1669855692000-resyncPatientAdditionalData';
import { wipeAllDataAndResync1675907161000 } from './1675907161000-wipeAllDataAndResync';
import { addLocationGroupTable1673396917000 } from './1673396917000-addLocationGroupTable';
import { addDepartmentIdToLabRequest1676853984000 } from './1676853984000-addDepartmentIdToLabRequest';
import { addNotGivenReasonIdColumnToAdministeredVaccineTable1678061990000 } from './1678061990000-addNotGivenReasonIdColumnToAdministeredVaccineTable';

export const migrationList = [
  databaseSetup1661160427226,
  updatePatientDateTimeColumns1661717539000,
  updateLabTestDate1662006885000,
  updatePatientIssueDate1663564207000,
  updatePatientEncounterDateTimeColumns1664229842000,
  alterModelsForV2Sync1663710579000,
  updateSurveyResponseDateTimeColumns1664475769000,
  changeCaseOfSpo21665717114000,
  updateLabRequestDateColumns1666171050000,
  addFieldUpdateTicksToPAD1668987530000,
  addDefaultLastSuccessfulSyncPull1669160460000,
  resyncPatientAdditionalData1669855692000,
  addLocationGroupTable1673396917000,
  wipeAllDataAndResync1675907161000,
  addDepartmentIdToLabRequest1676853984000,
  addNotGivenReasonIdColumnToAdministeredVaccineTable1678061990000,
];
