// This file is autogenerated, do not edit it directly
import { databaseSetup1661160427226 } from './1661160427226-databaseSetup';
import { updatePatientDateTimeColumns1661717539000 } from './1661717539000-updatePatientDateTimeColumns';
import { updateLabTestDate1662006885000 } from './1662006885000-updateLabTestDate';
import { updatePatientIssueDate1663564207000 } from './1663564207000-updatePatientIssueDate';
import { updatePatientEncounterDateTimeColumns1664229842000 } from './1664229842000-updatePatientEncounterDateTimeColumns';
import { alterModelsForV2Sync1663710579000 } from './1663710579000-alterModelsForV2Sync';
import { updateSurveyResponseDateTimeColumns1664475769000 } from './1664475769000-updateSurveyResponseDateTimeColumns';
import { updateLabRequestDateColumns1666171050000 } from './1666171050000-updateLabRequestDateColumns';

export const migrationList = [
  databaseSetup1661160427226,
  updatePatientDateTimeColumns1661717539000,
  updateLabTestDate1662006885000,
  updatePatientIssueDate1663564207000,
  updatePatientEncounterDateTimeColumns1664229842000,
  alterModelsForV2Sync1663710579000,
  updateSurveyResponseDateTimeColumns1664475769000,
  updateLabRequestDateColumns1666171050000,
];
