export function createDummyAefiProgramDataElements() {
  return [
    { id: 'dataElement/AEFI_02', code: 'AEFI_02', name: 'dataElement/AEFI_02' },
    { id: 'dataElement/AEFI_03', code: 'AEFI_03', name: 'dataElement/AEFI_03' },
    { id: 'dataElement/AEFI_04', code: 'AEFI_04', name: 'dataElement/AEFI_04' },
    { id: 'dataElement/AEFI_06', code: 'AEFI_06', name: 'dataElement/AEFI_06' },
    { id: 'dataElement/AEFI_07', code: 'AEFI_07', name: 'dataElement/AEFI_07' },
    { id: 'dataElement/AEFI_08', code: 'AEFI_08', name: 'dataElement/AEFI_08' },
    { id: 'dataElement/AEFI_09', code: 'AEFI_09', name: 'dataElement/AEFI_09' },
    { id: 'dataElement/AEFI_10', code: 'AEFI_10', name: 'dataElement/AEFI_10' },
    { id: 'dataElement/AEFI_11', code: 'AEFI_11', name: 'dataElement/AEFI_11' },
    { id: 'dataElement/AEFI_12', code: 'AEFI_12', name: 'dataElement/AEFI_12' },
    { id: 'dataElement/AEFI_13', code: 'AEFI_13', name: 'dataElement/AEFI_13' },
    { id: 'dataElement/AEFI_14', code: 'AEFI_14', name: 'dataElement/AEFI_14' },
    { id: 'dataElement/AEFI_15', code: 'AEFI_15', name: 'dataElement/AEFI_15' },
    { id: 'dataElement/AEFI_16', code: 'AEFI_16', name: 'dataElement/AEFI_16' },
    { id: 'dataElement/AEFI_17', code: 'AEFI_17', name: 'dataElement/AEFI_17' },
    { id: 'dataElement/AEFI_18', code: 'AEFI_18', name: 'dataElement/AEFI_18' },
    { id: 'dataElement/AEFI_19', code: 'AEFI_19', name: 'dataElement/AEFI_19' },
    { id: 'dataElement/AEFI_20', code: 'AEFI_20', name: 'dataElement/AEFI_20' },
    { id: 'dataElement/AEFI_21', code: 'AEFI_21', name: 'dataElement/AEFI_21' },
    { id: 'dataElement/AEFI_22', code: 'AEFI_22', name: 'dataElement/AEFI_22' },
    { id: 'dataElement/AEFI_24', code: 'AEFI_24', name: 'dataElement/AEFI_24' },
    { id: 'dataElement/AEFI_25', code: 'AEFI_25', name: 'dataElement/AEFI_25' },
  ];
}
