export function createDummyAefiSurveyScreenComponent() {
  return [
    { dataElementId: 'dataElement/AEFI_02', surveyId: 'program-aefi/survey-aefi_immunisation' },
    { dataElementId: 'dataElement/AEFI_03', surveyId: 'program-aefi/survey-aefi_immunisation' },
    { dataElementId: 'dataElement/AEFI_04', surveyId: 'program-aefi/survey-aefi_immunisation' },
    { dataElementId: 'dataElement/AEFI_06', surveyId: 'program-aefi/survey-aefi_immunisation' },
    { dataElementId: 'dataElement/AEFI_07', surveyId: 'program-aefi/survey-aefi_immunisation' },
    { dataElementId: 'dataElement/AEFI_08', surveyId: 'program-aefi/survey-aefi_immunisation' },
    { dataElementId: 'dataElement/AEFI_09', surveyId: 'program-aefi/survey-aefi_immunisation' },
    { dataElementId: 'dataElement/AEFI_10', surveyId: 'program-aefi/survey-aefi_immunisation' },
    { dataElementId: 'dataElement/AEFI_11', surveyId: 'program-aefi/survey-aefi_immunisation' },
    { dataElementId: 'dataElement/AEFI_12', surveyId: 'program-aefi/survey-aefi_immunisation' },
    { dataElementId: 'dataElement/AEFI_13', surveyId: 'program-aefi/survey-aefi_immunisation' },
    { dataElementId: 'dataElement/AEFI_14', surveyId: 'program-aefi/survey-aefi_immunisation' },
    { dataElementId: 'dataElement/AEFI_15', surveyId: 'program-aefi/survey-aefi_immunisation' },
    { dataElementId: 'dataElement/AEFI_16', surveyId: 'program-aefi/survey-aefi_immunisation' },
    { dataElementId: 'dataElement/AEFI_17', surveyId: 'program-aefi/survey-aefi_immunisation' },
    { dataElementId: 'dataElement/AEFI_18', surveyId: 'program-aefi/survey-aefi_immunisation' },
    { dataElementId: 'dataElement/AEFI_19', surveyId: 'program-aefi/survey-aefi_immunisation' },
    { dataElementId: 'dataElement/AEFI_20', surveyId: 'program-aefi/survey-aefi_immunisation' },
    { dataElementId: 'dataElement/AEFI_21', surveyId: 'program-aefi/survey-aefi_immunisation' },
    { dataElementId: 'dataElement/AEFI_22', surveyId: 'program-aefi/survey-aefi_immunisation' },
    { dataElementId: 'dataElement/AEFI_24', surveyId: 'program-aefi/survey-aefi_immunisation' },
    { dataElementId: 'dataElement/AEFI_25', surveyId: 'program-aefi/survey-aefi_immunisation' },
  ];
}
