const {
  isPresent,
  hasContent,
  takesIdForm,
  takesDateForm,
  isNumber,
  isEmail,
  fieldHasContent,
  constructIsOneOf,
  constructRecordExistsWithId,
  constructIsEmptyOr,
  constructIsLongerThan,
  constructIsValidJson,
} = require('./validatorFunctions');

module.exports = {
  ObjectValidator: require('./ObjectValidator'),
  isPresent,
  hasContent,
  takesIdForm,
  takesDateForm,
  isNumber,
  isEmail,
  fieldHasContent,
  constructIsOneOf,
  constructRecordExistsWithId,
  constructIsEmptyOr,
  constructIsLongerThan,
  constructIsValidJson,
};
