import { describe, expect, it } from 'vitest';

import { ADMINISTRATION_STATUS } from '@tamanu/constants';
import getShowDoseInfo, {
  hasVisibleMarStatusIcon,
} from '../../../../app/components/Medication/Mar/getShowDoseInfo';

describe('hasVisibleMarStatusIcon', () => {
  const base = {
    isDiscontinued: false,
    isEnd: false,
    isPast: false,
    isPaused: false,
    isPrn: false,
  };

  it('is false when there is no marInfo', () => {
    expect(hasVisibleMarStatusIcon({ ...base, marInfo: null })).toBe(false);
  });

  it('is false for an empty due dose (no status, not past)', () => {
    expect(
      hasVisibleMarStatusIcon({
        ...base,
        marInfo: { id: '1' },
      }),
    ).toBe(false);
  });

  it('is true for given and not-given', () => {
    expect(
      hasVisibleMarStatusIcon({
        ...base,
        marInfo: { id: '1', status: ADMINISTRATION_STATUS.GIVEN },
      }),
    ).toBe(true);
    expect(
      hasVisibleMarStatusIcon({
        ...base,
        marInfo: { id: '1', status: ADMINISTRATION_STATUS.NOT_GIVEN },
      }),
    ).toBe(true);
  });

  it('is true for missed (past, no status, not PRN)', () => {
    expect(
      hasVisibleMarStatusIcon({
        ...base,
        isPast: true,
        marInfo: { id: '1' },
      }),
    ).toBe(true);
  });

  it('is false for past PRN with no status (no missed icon)', () => {
    expect(
      hasVisibleMarStatusIcon({
        ...base,
        isPast: true,
        isPrn: true,
        marInfo: { id: '1' },
      }),
    ).toBe(false);
  });

  it('is false when ended, discontinued, or paused without status', () => {
    expect(
      hasVisibleMarStatusIcon({
        ...base,
        isEnd: true,
        marInfo: { id: '1' },
      }),
    ).toBe(false);
    expect(
      hasVisibleMarStatusIcon({
        ...base,
        isDiscontinued: true,
        marInfo: { id: '1' },
      }),
    ).toBe(false);
    expect(
      hasVisibleMarStatusIcon({
        ...base,
        isPaused: true,
        marInfo: { id: '1' },
      }),
    ).toBe(false);
  });

  it('does not treat pending as a visible icon', () => {
    // No status and not past → empty; pending icon is unused
    expect(
      hasVisibleMarStatusIcon({
        ...base,
        marInfo: { id: '1', isAutoGenerated: true },
      }),
    ).toBe(false);
  });
});

describe('getShowDoseInfo', () => {
  const selectedDate = new Date(2026, 6, 23);
  const timeSlot = { startTime: '14:00', endTime: '15:00' };
  const identity = date => date;
  const toMs = date => (date ? new Date(date).getTime() : null);

  const baseArgs = {
    medication: { dosingUnit: 'mg', doseAmount: 5 },
    timeSlot,
    selectedDate,
    nextMarInfo: null,
    pauseRecords: { data: [] },
    now: new Date(2026, 6, 23, 14, 30),
    toFacilityDateTime: identity,
    storedDateTimeToEpochMilliseconds: toMs,
  };

  it('is true for a due dose with marInfo and no status', () => {
    expect(
      getShowDoseInfo({
        ...baseArgs,
        marInfo: { id: '1', dueAt: '2026-07-23 14:00:00' },
      }),
    ).toBe(true);
  });

  it('is false once status is recorded', () => {
    expect(
      getShowDoseInfo({
        ...baseArgs,
        marInfo: {
          id: '1',
          dueAt: '2026-07-23 14:00:00',
          status: ADMINISTRATION_STATUS.GIVEN,
        },
      }),
    ).toBe(false);
  });

  it('is false when the sub-slot is past', () => {
    expect(
      getShowDoseInfo({
        ...baseArgs,
        now: new Date(2026, 6, 23, 15, 30),
        marInfo: { id: '1', dueAt: '2026-07-23 14:00:00' },
      }),
    ).toBe(false);
  });
});

describe('multi-slot overlay hide signal', () => {
  it('hides when any sub-slot has a visible status icon', () => {
    const subSlots = [
      { marInfo: { id: '1', status: ADMINISTRATION_STATUS.GIVEN }, isPast: false },
      { marInfo: { id: '2' }, isPast: false },
    ];
    const anyStatusIcon = subSlots.some(({ marInfo, isPast }) =>
      hasVisibleMarStatusIcon({
        marInfo,
        isDiscontinued: false,
        isEnd: false,
        isPast,
        isPaused: false,
        isPrn: false,
      }),
    );
    expect(anyStatusIcon).toBe(true);
  });

  it('stays visible when all sub-slots are empty', () => {
    const subSlots = [
      { marInfo: { id: '1' }, isPast: false },
      { marInfo: { id: '2' }, isPast: false },
    ];
    const anyStatusIcon = subSlots.some(({ marInfo, isPast }) =>
      hasVisibleMarStatusIcon({
        marInfo,
        isDiscontinued: false,
        isEnd: false,
        isPast,
        isPaused: false,
        isPrn: false,
      }),
    );
    expect(anyStatusIcon).toBe(false);
  });

  it('hides when a sub-slot is missed', () => {
    const anyStatusIcon = hasVisibleMarStatusIcon({
      marInfo: { id: '1' },
      isDiscontinued: false,
      isEnd: false,
      isPast: true,
      isPaused: false,
      isPrn: false,
    });
    expect(anyStatusIcon).toBe(true);
  });
});
