version: 2
sources:
  - name: tamanu
    schema: public
    description: "{{ doc('generic__schema') }}"
    tables:
      - name: settings
        description: "{{ doc('table__settings') }}"
        config:
          tags:
            - system
          meta:
            triggers:
              - notify_settings_changed
              - record_settings_changelog
              - set_settings_updated_at
              - set_settings_updated_at_sync_tick
        columns:
          - name: id
            data_type: uuid
            description: "{{ doc('generic__id') }} in settings."
            data_tests:
              - unique
              - not_null
          - name: created_at
            data_type: timestamp with time zone
            description: "{{ doc('generic__created_at') }} in settings."
            data_tests:
              - not_null
          - name: updated_at
            data_type: timestamp with time zone
            description: "{{ doc('generic__updated_at') }} in settings."
            data_tests:
              - not_null
          - name: deleted_at
            data_type: timestamp with time zone
            description: "{{ doc('generic__deleted_at') }} in settings."
          - name: key
            data_type: text
            description: "{{ doc('settings__key') }}"
            data_tests:
              - not_null
          - name: value
            data_type: jsonb
            description: "{{ doc('settings__value') }}"
          - name: facility_id
            data_type: character varying(255)
            description: "{{ doc('settings__facility_id') }}"
            data_tests:
              - relationships:
                  arguments:
                    to: source('tamanu', 'facilities')
                    field: id
          - name: updated_at_sync_tick
            data_type: bigint
            description: "{{ doc('generic__updated_at_sync_tick') }} in settings."
            data_tests:
              - not_null
          - name: scope
            data_type: text
            description: "{{ doc('settings__scope') }}"
            data_tests:
              - not_null
              - accepted_values:
                  arguments:
                    values:
                      - global
                      - central
                      - facility
