#!/usr/bin/env node

function generate(tables) {
  return tables.map(table => `
    insert into logs.changes (
      table_oid, table_schema, table_name,
      logged_at, record_created_at, record_updated_at, record_deleted_at,
      updated_by_user_id, record_id,
      record_data
    )
    select
      'public.${table}'::regclass::oid as table_oid,
      'public' as table_schema,
      '${table}' as table_name,

      t.updated_at as logged_at,
      coalesce(t.created_at, t.updated_at) as record_created_at,
      coalesce(t.updated_at, t.created_at) as record_updated_at,
      t.deleted_at as record_deleted_at,

      uuid_nil() as updated_by_user_id,
      t.id::text as record_id,

      to_jsonb(t) as record_data
    from ${table} t;
  `.trim().replaceAll(/^    /gm, '')).join('\n\n');
}

const TABLES = [
'administered_vaccines',
'appointment_schedules',
'appointments',
'assets',
'certifiable_vaccines',
'certificate_notifications',
'contributing_death_causes',
'departments',
'discharges',
'document_metadata',
'encounter_diagnoses',
'encounter_diets',
'encounter_pause_prescription_histories',
'encounter_pause_prescriptions',
'encounter_prescriptions',
'encounters',
'facilities',
'imaging_area_external_codes',
'imaging_request_areas',
'imaging_requests',
'imaging_results',
'invoice_discounts',
'invoice_insurer_payments',
'invoice_insurers',
'invoice_item_discounts',
'invoice_items',
'invoice_patient_payments',
'invoice_payments',
'invoice_products',
'invoices',
'ips_requests',
'lab_request_attachments',
'lab_requests',
'lab_test_panel_lab_test_types',
'lab_test_panel_requests',
'lab_test_panels',
'lab_test_types',
'lab_tests',
'location_groups',
'locations',
'medication_administration_record_doses',
'medication_administration_records',
'notifications',
'patient_additional_data',
'patient_allergies',
'patient_birth_data',
'patient_care_plans',
'patient_communications',
'patient_conditions',
'patient_contacts',
'patient_death_data',
'patient_facilities',
'patient_family_histories',
'patient_field_definition_categories',
'patient_field_definitions',
'patient_field_values',
'patient_issues',
'patient_ongoing_prescriptions',
'patient_program_registration_conditions',
'patient_secondary_ids',
'patients',
'permissions',
'prescriptions',
'procedures',
'program_data_elements',
'program_registries',
'program_registry_clinical_statuses',
'program_registry_condition_categories',
'program_registry_conditions',
'programs',
'reference_data',
'reference_data_relations',
'reference_drugs',
'reference_medication_templates',
'referrals',
'report_definition_versions',
'report_definitions',
'report_requests',
'roles',
'scheduled_vaccines',
'settings',
'socket_io_attachments',
'survey_response_answers',
'survey_responses',
'survey_screen_components',
'surveys',
'task_designations',
'task_template_designations',
'task_templates',
'tasks',
'templates',
'translated_strings',
'triages',
'user_designations',
'user_facilities',
'user_preferences',
'users',
];

console.log(generate(TABLES));
