export const globalTestSettings = {
  country: {
    name: 'Utopia',
    'alpha-2': 'UT',
    'alpha-3': 'UTO',
  },
  fhir: {
    worker: {
      heartbeat: 400,
      assumeDroppedAfter: '10 minutes',
    },
  },
  imagingTypes: {
    xRay: { label: 'X-Ray' },
    ctScan: { label: 'CT Scan' },
    ultrasound: { label: 'Ultrasound' },
    mri: { label: 'MRI' },
    ecg: { label: 'Electrocardiogram (ECG)' },
    holterMonitor: { label: 'Holter Monitor' },
    echocardiogram: { label: 'Echocardiogram' },
    mammogram: { label: 'Mammogram' },
    endoscopy: { label: 'Endoscopy' },
    fluroscopy: { label: 'Fluroscopy' },
    angiogram: { label: 'Angiogram' },
    colonoscopy: { label: 'Colonoscopy' },
    vascularStudy: { label: 'Vascular Study' },
    stressTest: { label: 'Treadmill' },
  },
  survey: {
    defaultCodes: {
      department: 'Emergency',
      location: 'Bed 1',
    },
  },
  features: {
    displayIcd10CodesInDischargeSummary: false,
    displayProcedureCodesInDischargeSummary: false,
    editPatientDisplayId: false,
    editPatientDetailsOnMobile: false,
    enableCovidClearanceCertificate: false,
    enableInvoicing: false,
    enableNoteBackdating: false,
    enablePatientDeaths: false,
    enableVitalEdit: false,
    fhirNewZealandEthnicity: false,
    hideOtherSex: false,
    idleTimeout: {
      enabled: false,
      refreshInterval: 150,
      timeoutDuration: 600,
      warningPromptDuration: 30,
    },
    mandatoryVitalEditReason: false,
    onlyAllowLabPanels: false,
    patientPlannedMove: false,
    quickPatientGenerator: false,
    registerNewPatient: false,
    tableAutoRefresh: { enabled: false, interval: 300 },
  },
};
