import { IMAGING_AREA_TYPES, REFERENCE_TYPES } from '@tamanu/constants';
import { ALLERGIES } from '@tamanu/database/demoData/allergies';
import { APPOINTMENT_TYPES } from '@tamanu/database/demoData/appointmentTypes';
import { CARE_PLANS } from '@tamanu/database/demoData/carePlan';
import { DIAGNOSES } from '@tamanu/database/demoData/diagnoses';
import { DISPOSITIONS } from '@tamanu/database/demoData/dispositions';
import { DRUGS } from '@tamanu/database/demoData/drugs';
import { LAB_SAMPLE_SITES } from '@tamanu/database/demoData/labSampleSites';
import { PROCEDURE_TYPES } from '@tamanu/database/demoData/procedureTypes';
import { SPECIMEN_TYPES } from '@tamanu/database/demoData/specimenTypes';
import { TRIAGE_DIAGNOSES } from '@tamanu/database/demoData/triageDiagnoses';
import { VILLAGES } from '@tamanu/database/demoData/villages';
import {
  CT_SCAN_IMAGING_AREAS,
  ULTRASOUND_IMAGING_AREAS,
  X_RAY_IMAGING_AREAS,
} from '@tamanu/database/demoData/imagingAreas';

type NamedDemoRecord = { name: string };

const names = (records: NamedDemoRecord[]) => records.map(({ name }) => name);
// DIAGNOSES and PROCEDURE_TYPES store name and code in one tab-separated string.
const namesBeforeTab = (records: NamedDemoRecord[]) =>
  records.map(({ name }) => name.split('\t')[0]);
const namesAfterTab = (records: NamedDemoRecord[]) =>
  records.map(({ name }) => name.split('\t')[1] ?? name);

// Covers the imaging area types with no demo data list of their own.
const GENERIC_IMAGING_AREA_NAMES = [
  'Head',
  'Neck',
  'Chest',
  'Abdomen',
  'Pelvis',
  'Spine',
  'Left shoulder',
  'Right shoulder',
  'Left knee',
  'Right knee',
  'Left hand',
  'Right hand',
  'Left foot',
  'Right foot',
  'Whole body',
];

export const REFERENCE_DATA_NAMES: Record<string, string[]> = {
  ...Object.fromEntries(
    Object.values(IMAGING_AREA_TYPES).map(areaType => [areaType, GENERIC_IMAGING_AREA_NAMES]),
  ),

  [REFERENCE_TYPES.ALLERGY]: names(ALLERGIES),
  [REFERENCE_TYPES.APPOINTMENT_TYPE]: names(APPOINTMENT_TYPES),
  [REFERENCE_TYPES.CARE_PLAN]: names(CARE_PLANS),
  [REFERENCE_TYPES.DIAGNOSIS]: namesBeforeTab(DIAGNOSES),
  [REFERENCE_TYPES.DISCHARGE_DISPOSITION]: names(DISPOSITIONS),
  [REFERENCE_TYPES.DRUG]: names(DRUGS),
  [REFERENCE_TYPES.LAB_SAMPLE_SITE]: names(LAB_SAMPLE_SITES),
  [REFERENCE_TYPES.PROCEDURE_TYPE]: namesAfterTab(PROCEDURE_TYPES),
  [REFERENCE_TYPES.SPECIMEN_TYPE]: names(SPECIMEN_TYPES),
  [REFERENCE_TYPES.TRIAGE_REASON]: names(TRIAGE_DIAGNOSES),
  [REFERENCE_TYPES.VILLAGE]: names(VILLAGES),
  [IMAGING_AREA_TYPES.CT_SCAN_IMAGING_AREA]: names(CT_SCAN_IMAGING_AREAS),
  [IMAGING_AREA_TYPES.ULTRASOUND_IMAGING_AREA]: names(ULTRASOUND_IMAGING_AREAS),
  [IMAGING_AREA_TYPES.X_RAY_IMAGING_AREA]: names(X_RAY_IMAGING_AREAS),

  [REFERENCE_TYPES.ARRIVAL_MODE]: [
    'Ambulance',
    'Walk-in',
    'Private vehicle',
    'Police',
    'Air ambulance',
    'Boat',
    'Inter-facility transfer',
    'Community health worker',
  ],
  [REFERENCE_TYPES.BOOKING_TYPE]: [
    'Standard consultation',
    'Extended consultation',
    'Day procedure',
    'Follow-up review',
    'Telehealth',
    'Home visit',
    'Outreach clinic',
  ],
  [REFERENCE_TYPES.CATCHMENT]: [
    'Northern Catchment',
    'Southern Catchment',
    'Eastern Catchment',
    'Western Catchment',
    'Central Catchment',
    'Coastal Catchment',
    'Highlands Catchment',
    'Islands Catchment',
  ],
  [REFERENCE_TYPES.CONTACT_RELATIONSHIP]: [
    'Spouse',
    'Parent',
    'Child',
    'Sibling',
    'Grandparent',
    'Guardian',
    'Aunt or uncle',
    'Cousin',
    'Neighbour',
    'Friend',
  ],
  [REFERENCE_TYPES.COUNTRY]: [
    'Australia',
    'Fiji',
    'Kiribati',
    'Nauru',
    'New Zealand',
    'Papua New Guinea',
    'Samoa',
    'Solomon Islands',
    'Tonga',
    'Tuvalu',
    'Vanuatu',
  ],
  [REFERENCE_TYPES.DESIGNATION]: [
    'Registered Nurse',
    'Enrolled Nurse',
    'Nurse Practitioner',
    'Midwife',
    'Medical Officer',
    'Senior Medical Officer',
    'Surgeon',
    'Anaesthetist',
    'Paediatrician',
    'Pharmacist',
    'Laboratory Technician',
    'Radiographer',
    'Community Health Worker',
    'Ward Clerk',
  ],
  [REFERENCE_TYPES.DIET]: [
    'Full ward diet',
    'Soft diet',
    'Pureed diet',
    'Fluids only',
    'Nil by mouth',
    'Diabetic diet',
    'Low salt',
    'Low protein',
    'High protein',
    'Gluten free',
    'Infant formula',
  ],
  [REFERENCE_TYPES.DISEASE_CODING]: ['ICD-10', 'ICD-11', 'SNOMED CT', 'ICPC-2', 'Local coding'],
  [REFERENCE_TYPES.DIVISION]: [
    'Northern Division',
    'Southern Division',
    'Eastern Division',
    'Western Division',
    'Central Division',
    'Highlands Division',
    'Islands Division',
    'Coastal Division',
  ],
  [REFERENCE_TYPES.ETHNICITY]: [
    'Melanesian',
    'Polynesian',
    'Micronesian',
    'Papuan',
    'Chinese',
    'European',
    'Indian',
    'Filipino',
    'Mixed heritage',
  ],
  [REFERENCE_TYPES.FAMILY_RELATION]: [
    'Mother',
    'Father',
    'Daughter',
    'Son',
    'Sister',
    'Brother',
    'Grandmother',
    'Grandfather',
    'Aunt',
    'Uncle',
  ],
  [REFERENCE_TYPES.IMAGING_TYPE]: [
    'X-Ray',
    'CT Scan',
    'Ultrasound',
    'MRI',
    'Mammogram',
    'ECG',
    'Echocardiogram',
    'Endoscopy',
    'Colonoscopy',
    'Angiogram',
  ],
  [REFERENCE_TYPES.INSURER]: [
    'National Health Insurance',
    'Public Service Scheme',
    'Pacific Health Cover',
    'Island Mutual',
    'Seafarers Fund',
    'Teachers Health Fund',
    'Veterans Scheme',
  ],
  [REFERENCE_TYPES.LAB_TEST_CATEGORY]: [
    'Haematology',
    'Biochemistry',
    'Microbiology',
    'Serology',
    'Urinalysis',
    'Parasitology',
    'Immunology',
    'Cytology',
  ],
  [REFERENCE_TYPES.LAB_TEST_LABORATORY]: [
    'Central Public Health Laboratory',
    'National Referral Laboratory',
    'Provincial Hospital Laboratory',
    'District Laboratory',
    'Mobile Testing Unit',
    'Partner Reference Laboratory',
  ],
  [REFERENCE_TYPES.LAB_TEST_METHOD]: [
    'Microscopy',
    'Culture',
    'Rapid diagnostic test',
    'PCR',
    'ELISA',
    'Immunoassay',
    'Spectrophotometry',
    'Flow cytometry',
  ],
  [REFERENCE_TYPES.LAB_TEST_PRIORITY]: ['Routine', 'Urgent', 'STAT', 'Pre-admission', 'Add-on'],
  [REFERENCE_TYPES.MANUFACTURER]: [
    'Serum Institute',
    'Bio Farma',
    'Sanofi Pasteur',
    'GlaxoSmithKline',
    'Pfizer',
    'Moderna',
    'Sinovac',
    'Bharat Biotech',
  ],
  [REFERENCE_TYPES.MEDICAL_AREA]: [
    'General Medicine',
    'Paediatrics',
    'Obstetrics',
    'Surgery',
    'Emergency',
    'Oncology',
    'Cardiology',
    'Renal',
    'Mental Health',
    'Rehabilitation',
  ],
  [REFERENCE_TYPES.MEDICATION_NOT_GIVEN_REASON]: [
    'Patient refused',
    'Patient absent',
    'Nil by mouth',
    'Out of stock',
    'Vomiting',
    'Adverse reaction',
    'Withheld by clinician',
    'Dose already given',
  ],
  [REFERENCE_TYPES.MEDICATION_PRESET_LABEL]: [
    'Post-operative analgesia',
    'Antenatal supplements',
    'Malaria treatment',
    'TB continuation phase',
    'Diabetes maintenance',
    'Hypertension maintenance',
    'Paediatric fever',
  ],
  [REFERENCE_TYPES.MEDICATION_SET]: [
    'Antenatal care set',
    'Emergency trolley set',
    'Post-operative set',
    'Paediatric ward set',
    'Malaria protocol set',
    'TB protocol set',
  ],
  [REFERENCE_TYPES.MEDICATION_TEMPLATE]: [
    'Paracetamol 500mg oral',
    'Amoxicillin 250mg oral',
    'Metformin 500mg oral',
    'Amlodipine 5mg oral',
    'Ceftriaxone 1g IV',
    'Ferrous sulfate 200mg oral',
    'Salbutamol inhaler',
    'Ondansetron 4mg IV',
  ],
  [REFERENCE_TYPES.NATIONALITY]: [
    'Australian',
    'Fijian',
    'I-Kiribati',
    'Nauruan',
    'New Zealander',
    'Papua New Guinean',
    'Samoan',
    'Solomon Islander',
    'Tongan',
    'Tuvaluan',
    'Ni-Vanuatu',
  ],
  [REFERENCE_TYPES.NOTE_TYPE]: [
    'Treatment plan',
    'Admission',
    'Discharge planning',
    'Clinical mobility',
    'Dietary',
    'Handover',
    'Nursing',
    'Pharmacy',
    'Physiotherapy',
    'Social welfare',
  ],
  [REFERENCE_TYPES.NURSING_ZONE]: [
    'Zone A',
    'Zone B',
    'Zone C',
    'North Wing',
    'South Wing',
    'Maternity Zone',
    'Paediatric Zone',
    'Critical Care Zone',
  ],
  [REFERENCE_TYPES.OCCUPATION]: [
    'Farmer',
    'Fisher',
    'Teacher',
    'Nurse',
    'Driver',
    'Shopkeeper',
    'Carpenter',
    'Police officer',
    'Public servant',
    'Student',
    'Homemaker',
    'Retired',
    'Unemployed',
  ],
  [REFERENCE_TYPES.PATIENT_BILLING_TYPE]: [
    'Public patient',
    'Private patient',
    'Insured',
    'Overseas visitor',
    'Staff',
    'Exempt',
  ],
  [REFERENCE_TYPES.PAYMENT_METHOD]: [
    'Cash',
    'Card',
    'Bank transfer',
    'Mobile money',
    'Cheque',
    'Insurance claim',
    'Waived',
  ],
  [REFERENCE_TYPES.PLACE_OF_BIRTH]: [
    'Born in facility',
    'Born before arrival',
    'Born at home',
    'Born in transit',
    'Born overseas',
  ],
  [REFERENCE_TYPES.REACTION]: [
    'Rash',
    'Hives',
    'Itching',
    'Swelling',
    'Anaphylaxis',
    'Nausea',
    'Vomiting',
    'Diarrhoea',
    'Shortness of breath',
    'Wheezing',
  ],
  [REFERENCE_TYPES.REFERRAL_SOURCE]: [
    'Self-referral',
    'General practitioner',
    'Community health worker',
    'Aid post',
    'District hospital',
    'Specialist clinic',
    'School health programme',
    'Outreach team',
  ],
  [REFERENCE_TYPES.RELIGION]: [
    'Catholic',
    'Lutheran',
    'United Church',
    'Seventh Day Adventist',
    'Anglican',
    'Pentecostal',
    'Baptist',
    'Evangelical',
    'Muslim',
    'Hindu',
    'None',
  ],
  [REFERENCE_TYPES.SECONDARY_ID_TYPE]: [
    'Passport',
    'Driving licence',
    'Birth certificate',
    'Voter card',
    'National ID',
    'Health card',
  ],
  [REFERENCE_TYPES.SETTLEMENT]: [
    'Riverside Settlement',
    'Hilltop Settlement',
    'Seaside Settlement',
    'Old Town',
    'New Town',
    'Market Ward',
    'Mission Station',
    'Airport Camp',
  ],
  [REFERENCE_TYPES.SUBDIVISION]: [
    'Kairuku District',
    'Rigo District',
    'Abau District',
    'Goilala District',
    'North Coast',
    'South Coast',
    'Upper Valley',
    'Lower Valley',
  ],
  [REFERENCE_TYPES.TASK_DELETION_REASON]: [
    'Entered in error',
    'Duplicate task',
    'Order cancelled',
    'Patient discharged',
    'Patient transferred',
    'No longer clinically indicated',
  ],
  [REFERENCE_TYPES.TASK_NOT_COMPLETED_REASON]: [
    'Patient refused',
    'Patient absent',
    'Patient asleep',
    'Equipment unavailable',
    'Staff unavailable',
    'Clinically deferred',
    'Patient off ward',
  ],
  [REFERENCE_TYPES.TASK_SET]: [
    'Admission observations',
    'Post-operative observations',
    'Antenatal observations',
    'Neurological observations',
    'Diabetic ward round',
    'Discharge checklist',
  ],
  [REFERENCE_TYPES.TASK_TEMPLATE]: [
    'Blood pressure check',
    'Temperature check',
    'Wound dressing change',
    'IV cannula check',
    'Catheter care',
    'Pressure area care',
    'Blood glucose check',
    'Fluid balance chart',
    'Medication round',
    'Mobilise patient',
  ],
  [REFERENCE_TYPES.VACCINE_CIRCUMSTANCE]: [
    'Routine schedule',
    'Catch-up',
    'Outbreak response',
    'Travel',
    'Occupational',
    'Campaign',
  ],
  [REFERENCE_TYPES.VACCINE_NOT_GIVEN_REASON]: [
    'Vaccine out of stock',
    'Patient unwell',
    'Parent refused',
    'Patient refused',
    'Contraindicated',
    'Cold chain failure',
    'Already vaccinated elsewhere',
  ],
};
