import { addHours, isSameDay } from 'date-fns';

import { ADMINISTRATION_STATUS, MEDICATION_ADMINISTRATION_TIME_SLOTS } from '@tamanu/constants';
import { getDateFromTimeString } from '@tamanu/shared/utils/medication';
import { useDateTime } from '@tamanu/ui-components';
import { useMarDoses } from '../../../api/queries/useMarDoses';
import { useAuth } from '../../../contexts/Auth';
import {
  useIsDiscontinued,
  useIsEnd,
  useIsPaused,
  useIsPausedThenDiscontinued,
} from './useMarStatusFlags';

const getIsPast = ({ timeSlot, selectedDate, now }) => {
  const slotEndDate = getDateFromTimeString(timeSlot.endTime, selectedDate);
  return now > slotEndDate;
};

const getIsCurrent = ({ timeSlot, selectedDate, now }) => {
  const slotStartDate = getDateFromTimeString(timeSlot.startTime, selectedDate);
  const slotEndDate = getDateFromTimeString(timeSlot.endTime, selectedDate);
  return now >= slotStartDate && now < slotEndDate;
};

const getIsNotDue = ({ hasRecord, timeSlot, selectedDate, now }) => {
  const slotStartDate = getDateFromTimeString(timeSlot.startTime, selectedDate);
  if (!hasRecord || !isSameDay(selectedDate, now)) {
    return slotStartDate > now;
  }
  return slotStartDate > addHours(now, 2);
};

/**
 * Derived per-dose MAR state shared by MarDoseButton and the MarStatus DoseInfo overlay.
 */
export function useMarDoseState({
  selectedDate,
  timeSlot,
  marInfo,
  previousMarInfo,
  nextMarInfo,
  medication,
  pauseRecords,
}) {
  const { data: { data: marDoses = [] } = {} } = useMarDoses(marInfo?.id);
  const { getFacilityNowDate, storedDateTimeToEpochMilliseconds } = useDateTime();
  const facilityNow = getFacilityNowDate();
  const { ability } = useAuth();
  const canViewMar = ability.can('read', 'MedicationAdministration');
  const canCreateMar = ability.can('create', 'MedicationAdministration');
  const canView =
    !medication?.medication?.referenceDrug?.isSensitive ||
    ability.can('read', 'SensitiveMedication');

  const { dueAt, recordedAt, status, reasonNotGiven, isAutoGenerated, isEdited } = marInfo || {};
  const { doseAmount, isPrn, dosingUnit, discontinuedDate, endDate, isVariableDose } =
    medication || {};

  const isPast = getIsPast({ timeSlot, selectedDate, now: facilityNow });
  const isNotDue = getIsNotDue({
    hasRecord: Boolean(marInfo),
    timeSlot,
    selectedDate,
    now: facilityNow,
  });
  const isFuture = getDateFromTimeString(timeSlot.startTime, selectedDate) > facilityNow;
  const isCurrent = getIsCurrent({ timeSlot, selectedDate, now: facilityNow });
  const isDiscontinued = useIsDiscontinued({
    discontinuedDate,
    dueAt,
    isRecordedStatus: Boolean(recordedAt),
    timeSlot,
    selectedDate,
    nextMarInfo,
  });
  const isEnd = useIsEnd({
    endDate,
    hasRecord: Boolean(marInfo),
    timeSlot,
    selectedDate,
  });
  const isPaused = useIsPaused({
    pauseRecords: pauseRecords?.data,
    timeSlot,
    selectedDate,
    recordedAt,
  });

  const previousTimeSlot = MEDICATION_ADMINISTRATION_TIME_SLOTS.find(
    slot => slot.endTime === timeSlot.startTime,
  );
  const isPreviouslyPaused = useIsPaused({
    pauseRecords: pauseRecords?.data,
    timeSlot: previousTimeSlot,
    selectedDate,
    recordedAt: previousMarInfo?.recordedAt,
  });

  const isPausedThenDiscontinued = useIsPausedThenDiscontinued({
    isPreviouslyPaused,
    isDiscontinued,
    timeSlot,
    selectedDate,
    discontinuedDate,
  });

  const recordedAtMs = storedDateTimeToEpochMilliseconds(recordedAt);
  const dueAtMs = storedDateTimeToEpochMilliseconds(dueAt);
  const isRecordedOutsideAdministrationSchedule =
    !isAutoGenerated ||
    (recordedAtMs != null && dueAtMs != null && recordedAtMs < dueAtMs) ||
    (isPrn && isPast);
  const isDoseAmountNotMatch =
    !isVariableDose &&
    status === ADMINISTRATION_STATUS.GIVEN &&
    marDoses?.some(dose => Number(dose.doseAmount) !== Number(doseAmount));
  const isRecordedDuringPaused = Boolean(recordedAt) && isPaused;
  const isMultipleDoses = marDoses?.length > 1;
  const isError = marInfo?.isError;
  const isAlert =
    Boolean(recordedAt) &&
    (isRecordedOutsideAdministrationSchedule ||
      isDoseAmountNotMatch ||
      isRecordedDuringPaused ||
      isMultipleDoses ||
      isError);

  const showDoseInfo =
    Boolean(marInfo) &&
    !status &&
    !isEnd &&
    !isDiscontinued &&
    !isPaused &&
    !isPast &&
    Boolean(dosingUnit);

  return {
    canCreateMar,
    canView,
    canViewMar,
    doseAmount,
    dosingUnit,
    dueAt,
    endDate,
    isAlert,
    isCurrent,
    isDiscontinued,
    isDoseAmountNotMatch,
    isEdited,
    isEnd,
    isError,
    isFuture,
    isNotDue,
    isPaused,
    isPausedThenDiscontinued,
    isPast,
    isPrn,
    isRecordedDuringPaused,
    isRecordedOutsideAdministrationSchedule,
    isVariableDose,
    marDoses,
    reasonNotGiven,
    showDoseInfo,
    status,
  };
}
