export const NON_SYNCING_TABLES = [
  'local_system_facts',
  'one_time_logins',
  'refresh_tokens',
  'patient_vrs_data',
  'SequelizeMeta',
  'signers',
  'sync_sessions',
  'sync_queued_devices',
  'user_localisation_caches',
  'fhir_materialise_jobs',
  'jobs',
  'job_workers',
  'user_recently_viewed_patients',
  'sync_lookup',
  'debug_logs',
  'sync_device_ticks',
  'sync_lookup_ticks'
];
