module.exports = {
  AllergyModel: require('./allergy'),
  AppointmentModel: require('./appointment'),
  DiagnosisModel: require('./diagnosis'),
  LabModel: require('./lab'),
  MedicationModel: require('./medication'),
  OperativePlanModel: require('./operativePlan'),
  OperationReportModel: require('./operationReport'),
  PatientModel: require('./patient'),
  PhotoModel: require('./photo'),
  ProcedureModel: require('./procedure'),
  PatientNoteModel: require('./patientNote'),
  ReportModel: require('./report'),
  UserRoleModel: require('./userRole'),
  UserModel: require('./user'),
  VitalModel: require('./vital'),
  VisitModel: require('./visit'),
};
