@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmMTZlZWNlNS04M2UzLTQ5MzUtYmE4NC0xNGZlZmQyYTQ2YTciLCJpYXQiOjE2MjQzNTIxNjJ9.E6d6_t4JI1SmdCpa7HMLyI1aFvia99Wqzp6cwNxvcVk
@server=sync.tamanu-nauru.org
@since=0

### Log in
POST {{server}}/v1/login
Content-Type: application/json

{
    "email": "admin@tamanu.io",
    "password": "admin"
}

### Get current user details
GET {{server}}/v1/whoami
Authorization: Bearer {{token}}

### List users
GET {{server}}/v1/sync/user?since={{since}}
Authorization: Bearer {{token}}

### Create an account
# The server will hash the password if provided
POST {{server}}/v1/sync/user
Content-Type: application/json
Authorization: Bearer {{token}}

[{
    "data": {
        "email": "my.email@domain.com",
        "password": "open-sesame",
        "displayName": "Test User",
        "role": "practitioner"
    }
}]

### Update user details (including changing a password)
POST {{server}}/v1/sync/user
Content-Type: application/json
Authorization: Bearer {{token}}

[{
    "data": {
        "id": "user-RajPrasad",
        "email": "raj.prasad@thepalladiumgroup.com"
    }
}]