@token=fake-token
@server=https://sync-demo.tamanu.io
@since=0

### Log in
POST {{server}}/v1/login
Content-Type: application/json

{
    "email": "",
    "password": ""
}

### Get current user details
GET {{server}}/v1/whoami
Authorization: Bearer {{token}}
