
# No token as labResultWidget is a public route.
# @token=fake-token
@server=http://localhost:3000

### Get the endpoint we're interested in
GET {{server}}/v1/public/labResultWidget/3TTW49  HTTP/1.1
# Authorization: Bearer {{token}}
