import { BIRTH_DELIVERY_TYPES, BIRTH_TYPES } from '@tamanu/constants';

export const BIRTH_DELIVERY_TYPE_LABELS = {
  [BIRTH_DELIVERY_TYPES.NORMAL_VAGINAL_DELIVERY]: 'Normal vaginal delivery',
  [BIRTH_DELIVERY_TYPES.BREECH]: 'Breech',
  [BIRTH_DELIVERY_TYPES.EMERGENCY_C_SECTION]: 'Emergency C-section',
  [BIRTH_DELIVERY_TYPES.ELECTIVE_C_SECTION]: 'Elective C-section',
  [BIRTH_DELIVERY_TYPES.VACUUM_EXTRACTION]: 'Vacuum extraction',
  [BIRTH_DELIVERY_TYPES.FORCEPS]: 'Forceps',
  [BIRTH_DELIVERY_TYPES.OTHER]: 'Other',
};

export const BIRTH_DELIVERY_TYPE_OPTIONS = [
  {
    value: BIRTH_DELIVERY_TYPES.NORMAL_VAGINAL_DELIVERY,
    label: BIRTH_DELIVERY_TYPE_LABELS[BIRTH_DELIVERY_TYPES.NORMAL_VAGINAL_DELIVERY],
  },
  {
    value: BIRTH_DELIVERY_TYPES.BREECH,
    label: BIRTH_DELIVERY_TYPE_LABELS[BIRTH_DELIVERY_TYPES.BREECH],
  },
  {
    value: BIRTH_DELIVERY_TYPES.EMERGENCY_C_SECTION,
    label: BIRTH_DELIVERY_TYPE_LABELS[BIRTH_DELIVERY_TYPES.EMERGENCY_C_SECTION],
  },
  {
    value: BIRTH_DELIVERY_TYPES.ELECTIVE_C_SECTION,
    label: BIRTH_DELIVERY_TYPE_LABELS[BIRTH_DELIVERY_TYPES.ELECTIVE_C_SECTION],
  },
  {
    value: BIRTH_DELIVERY_TYPES.VACUUM_EXTRACTION,
    label: BIRTH_DELIVERY_TYPE_LABELS[BIRTH_DELIVERY_TYPES.VACUUM_EXTRACTION],
  },
  {
    value: BIRTH_DELIVERY_TYPES.FORCEPS,
    label: BIRTH_DELIVERY_TYPE_LABELS[BIRTH_DELIVERY_TYPES.FORCEPS],
  },
  {
    value: BIRTH_DELIVERY_TYPES.OTHER,
    label: BIRTH_DELIVERY_TYPE_LABELS[BIRTH_DELIVERY_TYPES.OTHER],
  },
];

export const BIRTH_TYPE_LABELS = {
  [BIRTH_TYPES.SINGLE]: 'Single',
  [BIRTH_TYPES.PLURAL]: 'Plural',
};

export const BIRTH_TYPE_OPTIONS = [
  { value: BIRTH_TYPES.SINGLE, label: BIRTH_TYPE_LABELS[BIRTH_TYPES.SINGLE] },
  { value: BIRTH_TYPES.PLURAL, label: BIRTH_TYPE_LABELS[BIRTH_TYPES.PLURAL] },
];
