export const testData = {
  village: "Dama",
  villageId: "village-Dama",
  department: "Cardiology",
  departmentId: "department-Cardiology",
  encounterType: "admission",
  locationId: "location-EDBed1-tamanu",
  patientBillingTypeId: "patientType-Private",
  patientId: undefined,
  areaName: "Emergency Department",
  dietName:"Carbohydrate controlled",
  dietName2:"Citrus free",
  dietSearchResult1:"CarbControlled",
  dietSearchResult2:"Citrusfree",
};
