name: Branch info

on:
  workflow_call:
    outputs:
      branch:
        value: ${{ jobs.run.outputs.branch }}
      actual_ref:
        value: ${{ github.event.pull_request.head.ref || github.ref }}
      version:
        value: ${{ jobs.version.outputs.version }}

jobs:
  run:
    name: Branch name
    runs-on: ubuntu-latest
    steps:
      - name: Normalise branch/ref name
        uses: actions/github-script@v6
        id: ref
        env:
          GH_HEAD_REF: ${{ github.head_ref }}
          GH_REF_NAME: ${{ github.ref_name }}
        with:
          result-encoding: string
          script: |
            return ((process.env.GH_HEAD_REF || process.env.GH_REF_NAME)
              .toLowerCase()
              .replace(/[^a-z0-9-]/g, '-')
              .replace(/-+/g, '-')
              .replace(/^-|-$/g, ''));
    outputs:
      branch: ${{ steps.ref.outputs.result }}

  version:
    name: Version
    needs: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}

      # if the checkout fails, we're most likely on a workflow from a deleted
      # branch from a merged PR, so checkout main instead. This could yield
      # wrong version information but the only workflow where this can happen
      # at writing is "CD Down", which doesn't use version info.
      - if: failure()
        uses: actions/checkout@v2
        with:
          ref: main

      - uses: actions/github-script@v6
        id: version
        with:
          result-encoding: string
          script: return require('./package.json').version;
    outputs:
      version: ${{ steps.version.outputs.result }}
