name: Branch info

on:
  workflow_call:
    outputs:
      branch:
        value: ${{ jobs.run.outputs.branch }}
      actual_ref:
        value: ${{ github.event.pull_request.head.ref || github.ref }}

jobs:
  run:
    name: Branch name
    runs-on: ubuntu-latest
    steps:
      - name: Normalise branch/ref name
        uses: actions/github-script@v6
        id: ref
        env:
          GH_HEAD_REF: ${{ github.head_ref }}
          GH_REF_NAME: ${{ github.ref_name }}
        with:
          result-encoding: string
          script: |
            return ((process.env.GH_HEAD_REF || process.env.GH_REF_NAME)
              .toLowerCase()
              .replace(/[^a-z0-9-]/g, '-')
              .replace(/-+/g, '-')
              .replace(/^-|-$/g, ''));
    outputs:
      branch: ${{ steps.ref.outputs.result }}
