name: Build shared

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-shared:
    strategy:
      fail-fast: false
      matrix:
        os:
          # - macos
          - ubuntu
          # - windows
        node:
          - '16.x'

    name: Build shared os=${{ matrix.os }} node=${{ matrix.node }}
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
        cache: yarn

    - run: yarn
    - run: yarn build-shared
    
    - name: Pack shared + node_modules
      run: |
        set -e
        tar cf shared.tar node_modules packages/*/node_modules packages/shared
        zstd shared.tar

    - uses: actions/upload-artifact@v3
      with:
        retention-days: 1
        name: "shared_${{ runner.os }}_${{ matrix.node }}"
        path: shared.tar.zst