name: CD Containers

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - dev
      - main

env:
  NODE_OPTIONS: '--max-old-space-size=6144'
  NODE_ENV: test

permissions:
  contents: read
  id-token: write # OIDC token for ECR login

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          # - linux/arm64
        package:
          - name: central
            path: sync-server
          # - name: facility
          #   path: lan
          # - name: meta
          #   path: meta-server

    name: Build ${{ matrix.package.name }} container for ${{ matrix.platform }}
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::143295493206:role/gha-build
          role-session-name: GithubActionsTamanuBuild

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      
      - uses: actions/github-script@v6
        id: image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPO_NAME: ${{ matrix.package.name }}
        with:
          result-encoding: string
          script: |
            const registry = process.env.REGISTRY;
            const repo_name = process.env.REPO_NAME;
            const image = `${registry}/tamanu/${repo_name}`;
            console.log({ registry, repo_name, image });
            return image;
      - uses: actions/github-script@v6
        id: ref
        env:
          GH_HEAD_REF: ${{ github.head_ref }}
          GH_REF_NAME: ${{ github.ref_name }}
        with:
          result-encoding: string
          script: |
            const head_ref = process.env.GH_HEAD_REF;
            const ref_name = process.env.GH_REF_NAME;
            const ref = head_ref ?? ref_name;
            console.log({ head_ref, ref_name, ref });
            const cleaned = ref
              .replace(/[^a-z0-9-]/g, '-')
              .replace(/-+/g, '-')
              .replace(/^-|-$/g, '');
            console.log({ cleaned });
            return cleaned;

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ matrix.platform }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: PACKAGE_PATH=${{ matrix.package.path }}
          push: true
          tags: |
            ${{ steps.image.outputs.result }}:${{ github.sha }}
            ${{ steps.image.outputs.result }}:${{ steps.ref.outputs.result }}
