name: CD Containers

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - dev
      - main

env:
  NODE_OPTIONS: "--max-old-space-size=6144"
  NODE_ENV: test

permissions:
  contents: read
  id-token: write # OIDC token for ECR login

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        package:
          - name: central
            path: sync-server
          - name: facility
            path: lan
          - name: meta
            path: meta-server

    name: Build ${{ matrix.package.name }} container for ${{ matrix.platform }}
    runs-on: ubuntu-latest

    steps:
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ap-southeast-2
        role-to-assume: arn:aws:iam::143295493206:role/gha-build
        role-session-name: GithubActionsTamanuBuild

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - uses: actions/checkout@v3
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: ${{ matrix.platform }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: PACKAGE_PATH=${{ matrix.package.path }}
        push: true
        tags: |
          ${{ steps.login-ecr.outputs.registry }}/tamanu/${{ matrix.package.name }}:${{ github.sha }}
          ${{ steps.login-ecr.outputs.registry }}/tamanu/${{ matrix.package.name }}:${{ github.ref_name }}
