name: CD Containers

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - dev
      - main

env:
  NODE_OPTIONS: "--max-old-space-size=6144"
  NODE_ENV: test

jobs:
  build:
    name: Build containers
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ap-southeast-2
        role-to-assume: arn:aws:iam::143295493206:role/gha-build
        role-session-name: GithubActionsTamanuBuild

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - uses: actions/checkout@v3
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}:${{ github.sha }}
          ${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}:${{ github.ref_name }}
