name: CD Client

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - release/*

concurrency:
  # only one build or destroy at a time, per PR/branch, but don't cancel existing runs
  group: cd-${{ github.pull_request.id || github.ref }}

permissions:
  contents: read
  pull-requests: write
  id-token: write # OIDC token for AWS

jobs:
  info:
    name: Branch info
    uses: ./.github/workflows/branch-info.yml

  build:
    needs: info
    runs-on: ubuntu-latest
    name: Build desktop client
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::143295493206:role/gha-desktop-s3
          role-session-name: GithubActionsTamanuS3

      - uses: actions/checkout@v3
        with:
          # in PRs, use the actual PR branch, not the merge branch
          ref: ${{ github.event.pull_request.head.ref || github.ref }}

      - name: Setup buildkit
        uses: docker/setup-buildx-action@v2

      - name: Build container
        uses: docker/build-push-action@v4
        with:
          context: .
          cache-from: type=gha,scope=${{ needs.info.outputs.branch }}-desktop
          cache-to: type=gha,mode=max,scope=${{ needs.info.outputs.branch }}-desktop
          build-args: PACKAGE_PATH=desktop
          target: build-server
          push: false
          tags: working

      - name: Make output folders
        run: mkdir -p ops/win-{appdata,msi}

      - name: Start container
        run: |
          docker run -dit --rm --name working \
            -v $PWD/ops:/app/packages/desktop/release \
            working

      - name: Install build tooling
        run: |
          docker exec working bash -c "\
            wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub; \
            wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.35-r1/glibc-2.35-r1.apk; \
            apk add tar glibc-2.35-r1.apk libc6-compat 7zip squashfs-tools wine wine_gecko wine-mono --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing; \
            ln -s /usr/bin/7z{,a}; \
          "

      - name: Package for Linux, Windows (NSIS)
        run: |
          docker exec \
            -w /app/packages/desktop \
            -e USE_SYSTEM_7ZA=true \
            -e USE_SYSTEM_MKSQUASHFS=true \
            working \
              yarn run package-only --x64 --linux --win

      - name: Enable AppData install
        run: |
          docker exec -w /app/packages/desktop working \
            cp packages/desktop/app/package.json{,.orig}
          docker exec -w /app/packages/desktop working \
            sh -c 'jq \'build.nsis.perMachine = true | build.directories.output = "release/win-appdata"\' \
              packages/desktop/app/package.json.orig > packages/desktop/app/package.json'

      - name: Package for Windows (AppData)
        run: |
          docker exec \
            -w /app/packages/desktop \
            -e USE_SYSTEM_7ZA=true \
            working \
              yarn run package-only --win --x64

      - name: Stop container
        run: docker kill working

      - name: Remove unpacked outputs
        run: |
          sudo chown -R $USER:$USER ops
          rm -rf ops/**/*-unpacked

      - name: Upload as artifact
        uses: actions/upload-artifact@v3
        with:
          name: tamanu-desktop
          path: ops/*
          retention-days: 14

      - name: Push to S3
        working-directory: packages/desktop
        run: aws s3 cp tamanu-*.zip s3://${{ vars.DESKTOP_S3_BUCKET }}/${{ needs.info.outputs.branch }} --no-progress
