name: CD Package Patient Portal

on:
  workflow_call:
    secrets:
      META_CERT:
        required: true
      META_KEY:
        required: true

permissions:
  packages: read # to pull image
  contents: write # to update the release
  id-token: write # OIDC token for AWS

jobs:
  pack:
    runs-on: ubuntu-latest
    name: Pack patient-portal
    steps:
      - name: Login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Pull image
        run: docker pull ghcr.io/beyondessential/tamanu-patient-portal:sha-${{ github.sha }}.amd64

      - name: Extract version from image
        id: version
        run: |
          set -x
          docker image inspect ghcr.io/beyondessential/tamanu-patient-portal:sha-${{ github.sha }}.amd64 \
            | jq '"version=\(.[0] | .Config.Labels["org.opencontainers.image.version"])"' -r | tee -a "$GITHUB_OUTPUT"

      - name: Extract build from image and pack it
        run: |
          set -x

          docker create --name patient-portal ghcr.io/beyondessential/tamanu-patient-portal:sha-${{ github.sha }}.amd64
          docker cp patient-portal:/app tamanu-patient-portal-${{ steps.version.outputs.version }}
          docker rm patient-portal

          zip -r -0 tamanu-patient-portal-${{ steps.version.outputs.version }}.zip tamanu-patient-portal-${{ steps.version.outputs.version }}
          tar -cf patient-portal-${{ steps.version.outputs.version }}.tar tamanu-patient-portal-${{ steps.version.outputs.version }}
          zstd --rm --adapt -T0 -10 patient-portal-${{ steps.version.outputs.version }}.tar

      - name: Upload to artifact
        uses: actions/upload-artifact@v4
        with:
          name: patient-portal-package
          path: patient-portal*.tar.zst*
          retention-days: 15
          if-no-files-found: error

      - name: Set S3 destination
        id: destination
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            if (context.ref.startsWith('refs/tags/v')) {
              return `${context.ref.replace('refs/tags/v', '')}`;
            } else {
              return 'nowhere';
            }

      - name: Configure AWS Credentials (upload)
        if: steps.destination.outputs.result != 'nowhere'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::143295493206:role/gha-server-s3
          role-session-name: GHA@Tamanu=PatientPortalPackage

      - name: Push to S3
        if: steps.destination.outputs.result != 'nowhere'
        env:
          target: ${{ steps.destination.outputs.result }}
        run: |
          set -x
          for file in *.tar.zst*; do
            aws s3 cp $file s3://bes-tamanu-release-servers/$target/$file --no-progress
          done

      - name: Upload to release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: '*.tar.zst*'

      - uses: actions/checkout@v4
      - name: Post to meta
        if: steps.destination.outputs.result != 'nowhere' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        continue-on-error: true
        uses: ./.github/actions/meta-api
        with:
          url: ${{ vars.META_URL }}
          crt: ${{ secrets.META_CERT }}
          key: ${{ secrets.META_KEY }}
          api: /artifacts/${{ steps.destination.outputs.result }}/patient-portal/any
          arg: --data-binary 'https://servers.ops.tamanu.io/${{ steps.destination.outputs.result }}/patient-portal-${{ steps.version.outputs.version }}.tar.zst'
