name: CD Server Zips

on:
  workflow_dispatch:
  push:
    branches:
      - feature/epi-571-add-workflow-to-build-server-zips
    tags:
      - v*.*.*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  id-token: write # OIDC token for AWS

jobs:
  info:
    name: Branch info
    uses: ./.github/workflows/branch-info.yml

  image:
    needs: info
    uses: ./.github/workflows/build-image.yml
    strategy:
      matrix:
        package:
          - name: central
            path: sync-server
          - name: facility
            path: lan
    with:
      package-name: ${{ matrix.package.name }}
      package-path: ${{ matrix.package.path }}
      image-shatag: false
      image-tags: ${{ needs.info.outputs.version }}-serverzips

  build:
    needs:
      - info
      - image
    strategy:
      fail-fast: false
      matrix:
        package:
          - name: central
            path: sync-server
          - name: facility
            path: lan

    name: Build ${{ matrix.package.name }}
    runs-on: ubuntu-latest
    env:
      BUILD_NAME: "${{ matrix.package.name }}-${{ needs.info.outputs.version }}-build"

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::143295493206:role/gha-image-pull
          role-session-name: GHA@Tamanu=ServerZips
          mask-aws-account-id: false

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Create container
        run: docker create --name working --platform linux/amd64 ${{ needs.image.outputs.registry }}/tamanu/${{ matrix.package.name }}:${{ needs.info.outputs.version }}-serverzips

      - name: Copy files
        run: docker cp working:/app $BUILD_NAME

      - name: Remove dependencies
        working-directory: ${{ env.BUILD_NAME }}
        run: |
          set -ex
          rm -rf node_modules packages/*/node_modules

      - name: Delete container
        run: docker rm working

      - name: Prepare production configuration
        run: |
          set -ex
          ls packages/${{ matrix.package.path }}/config
          sed -E \
            "s|cwd: '.',( //.*)?|cwd: 'packages/${{ matrix.package.path }}',|" \
            packages/${{ matrix.package.path }}/pm2.config.js > ${{ env.BUILD_NAME }}/pm2.config.js

      - name: Prepare final output
        run: zip -r '${{ env.BUILD_NAME }}.zip' '${{ env.BUILD_NAME }}'

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BUILD_NAME }}
          path: '${{ env.BUILD_NAME }}.zip'

  windows-zip:
    needs: 
      - info
      - image
      - build
    strategy:
      fail-fast: false
      matrix:
        package:
          - name: central
            path: sync-server
          - name: facility
            path: lan

    name: Build ${{ matrix.package.name }} windows zip
    runs-on: windows-latest
    env:
      BUILD_NAME: "${{ matrix.package.name }}-${{ needs.info.outputs.version }}-build"
      OUTPUT_NAME: "test-2-${{ matrix.package.name }}-${{ needs.info.outputs.version }}-windows"
      S3_PATH: s3://bes-tamanu-release-servers/test/${{ needs.info.outputs.version }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.BUILD_NAME }}
          
      - name: Unzip artifact for deployment
        shell: bash
        run: unzip '${{ env.BUILD_NAME }}.zip'

      - name: Reinstall dependencies
        working-directory: ${{ env.BUILD_NAME }}
        shell: bash
        run: |
          set -ex
          yarn config set network-timeout 600000 -g
          yarn install --frozen-lockfile --production

      - name: Prepare final output
        shell: bash
        run: |
          set -ex
          ls
          command -v zip
          command -v unzip
          command -v tar
          zip -r '${{ env.OUTPUT_NAME }}.zip' '${{ env.BUILD_NAME }}'

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: debug
          path: '${{ env.OUTPUT_NAME }}.zip'
          retention-days: 1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::143295493206:role/gha-server-s3
          role-session-name: GHA@Tamanu=ServerZips
          mask-aws-account-id: false

      - name: Push to S3
        run: aws s3 cp '${{ env.OUTPUT_NAME }}.zip' '${{ env.S3_PATH }}/${{ env.OUTPUT_NAME }}.zip' --no-progress
