name: CD Server Package

on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*
    branches:
      - fix/bundle-desktop-with-release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write # for cd-client workflow, unused
  pull-requests: write # for cd-client workflow, unused
  id-token: write # OIDC token for AWS

jobs:
  info:
    name: Branch info
    uses: ./.github/workflows/branch-info.yml

  desktop:
    name: Desktop client
    uses: ./.github/workflows/cd-client.yml

  image:
    needs: info
    uses: ./.github/workflows/build-image.yml
    strategy:
      matrix:
        package:
          - name: central
            path: sync-server
          - name: facility
            path: lan
    with:
      package-name: ${{ matrix.package.name }}
      package-path: ${{ matrix.package.path }}
      image-shatag: false
      image-tags: ${{ needs.info.outputs.version }}-serverzips

  build:
    needs:
      - info
      - image
    strategy:
      fail-fast: false
      matrix:
        package:
          - name: central
            path: sync-server
          - name: facility
            path: lan

    name: Build ${{ matrix.package.name }}
    runs-on: ubuntu-latest
    env:
      BUILD_NAME: "release-${{ needs.info.outputs.version }}"
      ARTIFACT_NAME: "${{ matrix.package.name }}-${{ needs.info.outputs.version }}"

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::143295493206:role/gha-image-pull
          role-session-name: GHA@Tamanu=ServerZips
          mask-aws-account-id: false

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Create container
        run: docker create --name working --platform linux/amd64 ${{ needs.image.outputs.registry }}/tamanu/${{ matrix.package.name }}:${{ needs.info.outputs.version }}-serverzips

      - name: Copy files
        run: docker cp working:/app $BUILD_NAME

      - name: Remove dependencies
        working-directory: ${{ env.BUILD_NAME }}
        run: |
          set -ex
          rm -rf node_modules packages/*/node_modules

      - name: Delete container
        run: docker rm working

      # This will replace the line "cwd: '.'" for the appropriate package, i.e.
      # "cwd: 'packages/lan'" in the new build folder for each pm2.config file.
      - name: Prepare production configuration
        run: |
          set -ex
          sed -E \
            "s|cwd: '.',( //.*)?|cwd: 'packages/${{ matrix.package.path }}',|" \
            packages/${{ matrix.package.path }}/pm2.config.js > ${{ env.BUILD_NAME }}/pm2.config.js

      - name: Prepare artifact output
        run: zip -r '${{ env.BUILD_NAME }}.zip' '${{ env.BUILD_NAME }}'

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: '${{ env.BUILD_NAME }}.zip'
          retention-days: 1

  windows-zip:
    needs:
      - info
      - image
      - build
      - desktop
    strategy:
      fail-fast: false
      matrix:
        package:
          - name: central
            path: sync-server
          - name: facility
            path: lan

    name: Build ${{ matrix.package.name }} windows zip
    runs-on: windows-latest
    env:
      BUILD_NAME: "release-${{ needs.info.outputs.version }}"
      ARTIFACT_NAME: "${{ matrix.package.name }}-${{ needs.info.outputs.version }}"
      OUTPUT_NAME: "${{ matrix.package.name }}-${{ needs.info.outputs.version }}-windows"
      S3_PATH: s3://bes-tamanu-release-servers/${{ needs.info.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}

      - name: Unzip artifact for deployment
        shell: bash
        run: unzip '${{ env.BUILD_NAME }}.zip'

      - name: Reinstall dependencies
        working-directory: ${{ env.BUILD_NAME }}
        shell: bash
        run: |
          set -ex
          yarn config set network-timeout 600000 -g
          yarn install --frozen-lockfile --production

      - name: Download desktop client artifact
        uses: actions/download-artifact@v3
        with:
          name: desktop-client
          path: ${{ env.BUILD_NAME }}/packages/${{ matrix.package.path }}/upgrade

      - name: Prepare final output
        run: tar -caf '${{ env.OUTPUT_NAME }}.tar.gz' '${{ env.BUILD_NAME }}'

      - name: Prepare final output (xz)
        run: tar -caf '${{ env.OUTPUT_NAME }}.tar.xz' '${{ env.BUILD_NAME }}'

      - name: Prepare final output (zstd)
        run: tar -caf '${{ env.OUTPUT_NAME }}.tar.zst' '${{ env.BUILD_NAME }}'

      - name: Get minisign
        run: |
          set -ex
          curl --proto '=https' --tlsv1.2 -LO https://github.com/jedisct1/minisign/releases/download/0.11/minisign-0.11-linux.tar.gz
          echo 'f0a0954413df8531befed169e447a66da6868d79052ed7e892e50a4291af7ae0  minisign-0.11-linux.tar.gz' | sha256sum -c
          tar -xvf minisign-0.11-linux.tar.gz
          mv minisign-linux/x86_64/minisign .
      - name: Sign build
        env:
          MINISIGN_KEY: ${{ secrets.SIGNING_KEY }}
        run: |
          set -e
          echo "$MINISIGN_KEY" > minisign.key
          set -x
          ./minisign -R \
            -s minisign.key \
            -p minisign.pub
          ./minisign -S \
            -s minisign.key \
            -m '${{ env.OUTPUT_NAME }}.tar.zst' \
            -x '${{ env.OUTPUT_NAME }}.tar.zst.sig' \
            -t "built on $(date --iso-8601=seconds) from tamanu/$(git rev-parse HEAD)"
          rm minisign.*

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::143295493206:role/gha-server-s3
          role-session-name: GHA@Tamanu=ServerZips
          mask-aws-account-id: false

      - name: Push to S3
        run: aws s3 cp '${{ env.OUTPUT_NAME }}.tar.gz' '${{ env.S3_PATH }}/${{ env.OUTPUT_NAME }}.tar.gz' --no-progress
      - name: Push to S3
        run: aws s3 cp '${{ env.OUTPUT_NAME }}.tar.xz' '${{ env.S3_PATH }}/${{ env.OUTPUT_NAME }}.tar.xz' --no-progress
      - name: Push to S3
        run: |
          aws s3 cp '${{ env.OUTPUT_NAME }}.tar.zst' '${{ env.S3_PATH }}/${{ env.OUTPUT_NAME }}.tar.zst' --no-progress
          aws s3 cp '${{ env.OUTPUT_NAME }}.tar.zst.sig' '${{ env.S3_PATH }}/${{ env.OUTPUT_NAME }}.tar.zst.sig' --no-progress
