name: Check PR title

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  merge-to-main:
    name: When merging to main
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'main'
    steps:
    - name: Warn if feature PR title is not prefixed with ticket number
      if: startsWith(github.head_ref, 'feature/')
      run: |
        if [[ ! ${{ github.event.pull_request.title }} =~ ^[A-Z]+-[0-9]+ ]]; then
          echo "PR title should start with ticket number, e.g. 'ABC-123: ...'"
          exit 1
        fi
