name: Check PR title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize # temp for testing

jobs:
  merge-to-main:
    name: When merging to main
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'main' || github.event.pull_request.base.ref == 'dev'
    steps:
    - name: Warn if feature PR title is not prefixed with ticket number
      if: startsWith(github.head_ref, 'feature/')
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
      run: |
        if [[ ! "$PR_TITLE" =~ '^[A-Z]+-[0-9]+' ]]; then
          echo "::warning::PR title should start with ticket number, e.g. 'ABC-123: ...'"
        fi
