name: Container Image Cleanup

on:
  workflow_dispatch:
    inputs:
      ttl:
        description: 'How old in days a non-release image has to be before it’s deleted'
        required: true
        type: number
        default: 90
  schedule:
    # run around midnight australia/nz time
    - cron: '5 12 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: false

permissions:
  packages: write

jobs:
  config:
    name: Cleanup
    runs-on: ubuntu-latest
    steps:
      - uses: snok/container-retention-policy@v2
        with:
          image-names: tamanu-*
          cut-off: "${{ inputs.ttl || 90 }} days ago UTC"
          timestamp-to-use: updated_at
          account-type: org
          org-name: ${{ github.repository_owner }}
          keep-at-least: 1
          filter-tags: sha-*
          skip-tags: latest, v*
          token: ${{ secrets.GITHUB_TOKEN }}
