name: E2E Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: read
  pull-requests: write

jobs:
  check-e2e-request:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - uses: actions/checkout@v4
      - id: check
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.pull_request.body;
            const e2eMatch = body.match(/\[(?<checked>[ x])\]\s+\*\*Run E2E Tests\*\* <!-- #e2e -->/);
            core.setOutput('should_run', e2eMatch?.groups.checked === 'x');

  e2e:
    needs: check-e2e-request
    if: needs.check-e2e-request.outputs.should_run == 'true'
    name: E2E Tests (Shard ${{ matrix.shard }})
    strategy:
      fail-fast: false 
      matrix:
        shard: [1/4, 2/4, 3/4, 4/4]
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: tamanu
          POSTGRES_PASSWORD: tamanu
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U tamanu"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - uses: actions/cache/restore@v3
        with:
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          path: ${{ env.NODE_MODULES_PATHS }}

      - run: npm ci
      - run: npm run build
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Setup postgres dbs
        run: .github/scripts/e2e-test-setup.sh setup-postgres
      - name: Setup central server
        run: .github/scripts/e2e-test-setup.sh setup-central
      - name: Setup facility server
        run: .github/scripts/e2e-test-setup.sh setup-facility
      
      - name: Run Playwright tests
        run: npm run e2e-test -- -- --shard ${{ matrix.shard }}
        
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-shard-${{ matrix.shard }}
          path: |
            playwright-report/
            test-results/
          retention-days: 30