name: 'Build Android app'

on:
  pull_request:
  workflow_call:
    inputs:
      branding:
        type: string
        required: true
        default: tamanu
      server:
        type: string
        required: false

  workflow_dispatch:
    inputs:
      branding:
        description: Branding to use for app
        type: choice
        required: true
        default: tamanu
        options:
          - tamanu
          - cambodia
      server:
        description: Central server to use
        type: string
        required: false

env:
  BRANDING: ${{ inputs.branding || 'tamanu' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Update branding app title
        if: ${{ env.BRANDING == 'cambodia' }}
        working-directory: packages/mobile/android/app/src/main/res/values
        run: sed -i "s/Tamanu Mobile/KhmEIR/g" strings.xml

      - name: Set branding mipmap app icons
        working-directory: packages/mobile/android/app/src/main/res
        run: mv ${{env.BRANDING}}/* .

      - name: Set server overrides
        if: ${{ inputs.server }}
        working-directory: packages/mobile
        run: |
          echo \{\"centralServers\":[\{\"value\":\"${{inputs.server}}\", \"label\": \"Central Server\"\}]\} > serverOverrides.json

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      - name: Run Yarn Install
        working-directory: packages/mobile
        run: |
          npm i -g corepack
          yarn install

      - name: Build application
        working-directory: packages/mobile/android
        run: ./gradlew assembleDebug

      - name: Upload application
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ./packages/mobile/android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 3
