
name: Translations Diff

on:
  workflow_dispatch:

jobs:
  run:
    name:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - if: (!startsWith(github.ref, 'refs/heads/release/'))
        run: |
          echo "This workflow can only be run on a release branch"
          exit 1
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TAMANU_RELEASE_PAT }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Run search on TranslatedString components
        run: |
          git diff main -G"(stringId|fallback)" ./packages/web ./packages/mobile
