name: Test servers

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - dev
      - master
      - gha-test

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          # - macos
          - ubuntu
          # - windows
        node:
          - '16.x'
        postgres:
          # - '12'
          - '14'
        package:
          - sync-server
          - lan
          - meta-server
          - shared-src

    name: Test ${{ matrix.package }} os=${{ matrix.os }} node=${{ matrix.node }} pg=${{ matrix.postgres }}
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
        cache: 'yarn'

    - name: Install postgres ${{ matrix.postgres }}
      shell: bash
      run: .github/scripts/install-postgres-${{ matrix.os }}.sh ${{ matrix.postgres }}

    - name: Configure yarn workspaces
      shell: bash
      run: |
        yarn config set workspaces-experimental true
        yarn config set workspaces-nohoist-experimental true

    - run: yarn
    - run: yarn build-shared

    - run: yarn workspace ${{ matrix.package }} test